exports = EMAIL_STRING = {
  template_string: "YeePeey Support",
  app_name_string: "YeePeey",
};

exports = DELIVERY_TYPE = {
  STORE: 1,
  // COURIER: 2
};

exports = IMPORT_STORE_DATA = {
  PRODUCT: 21,
  ITEM: 22,
  SPECIFICATION_GROUP: 23,
  SPECIFICATION: 24,
  ITEM_SPECIFICATION: 25,
  UPDATE_ITEM_SPECIFICATION: 26,
  UPDATE_ITEM_PRICE_DESC: 27,
};

exports = SETTINGS_DETAILS = {};

exports = DATE_FORMATE = {
  DDMMYYYY: "DDMMYYYY",
  dmmmyy: "d-mmm-yy",
  ddmmyy: "dd/mm/yy",
  MMM_D_YYYY: "MMM D, YYYY",
  YYYY_MM_DD_HH_MM_SS: "YYYY-MM-DD hh:mm:ss",
  DDMMhhmm: "DDMMhhmm",
  MMM_d_YYYY: "MMM d YYYY",
};

exports = IMAGE_FILE_NAME = {
  LOGO_IMAGE_NAME: "logo.png",
  TITLE_IMAGE_NAME: "title_image.png",
  MAIL_TITLE_IMAGE_NAME: "email_vector.png",
  STORE_LOGO_IMAGE_NAME: "store_logo.png",
  MAIL_LOGO_IMAGE_NAME: "mail_logo.png",
  USER_LOGO_IMAGE_NAME: "user_logo.png",
};

exports = SMS_UNIQUE_ID = {
  USER_OTP: 1,
  USER_FORGOT_PASSWORD: 2,
  USER_ORDER_BOOKED: 3,
  USER_ORDER_READY: 4,
  USER_ORDER_DISPATCH: 5,
  USER_ORDER_CANCELLED: 6,
  USER_ORDER_DIGITAL_CODE: 7,
  USER_DECLINE: 8,
  USER_APPROVED: 9,
  USER_EMERGENCY_HELP: 10,
  USER_PAYMENT_REMAINING: 11,
  USER_PAYMENT_REFUND: 12,
  PROVIDER_OTP: 21,
  PROVIDER_FORGOT_PASSWORD: 22,
  PROVIDER_APPROVED: 23,
  PROVIDER_DECLINE: 24,
  PROVIDER_ORDER_CANCELLED: 25,
  PROVIDER_ORDER_REMAINING: 26,
  PROVIDER_EMERGENCY_HELP: 27,
  STORE_OTP: 41,
  STORE_FORGOT_PASSWORD: 42,
  STORE_APPROVED: 43,
  STORE_DECLINE: 44,
  STORE_ORDER_COMPLETED: 45,
  STORE_ORDER_CANCELLED: 46,
  STORE_ORDER_REMAINING: 47,
  STORE_PAYMENT_REMAINING: 48,
  STORE_PAYMENT_REFUND: 49,

  DELIVERY_MAN_ACCEPTED: 51,
  DELIVERY_MAN_COMING: 52,
  DELIVERY_MAN_ARRIVED: 53,

  DELIVERY_MAN_STARTED_DELIVERY: 54,
  DELIVERY_MAN_REACHED_AT_DESTINATION: 55,

  DELIVERY_MAN_ON_THE_WAY: 13,
  DELIVERY_MAN_ARRIVED_AT_DESTINATION: 14,

  NEW_ORDER: 50,
  USER_ORDER_PREPARE: 15,
  USER_ORDER_REJECTED: 16,

  ORDER_ASSIGN: 28,
  PROVIDER_NEW_ORDER: 29,
};
exports = EMAIL_UNIQUE_ID = {
  USER_WELCOME: 1,
  USER_APPROVED: 2,
  USER_OTP_VERIFICATION: 3,
  USER_FORGOT_PASSWORD: 4,
  USER_DECLINED: 6,

  PROVIDER_WELCOME: 11,
  PROVIDER_APPROVED: 12,
  PROVIDER_OTP_VERIFICATION: 13,
  PROVIDER_FORGOT_PASSWORD: 14,
  PROVIDER_DECLINED: 16,

  STORE_WELCOME: 21,
  STORE_APPROVED: 22,
  STORE_OTP_VERIFICATION: 23,
  STORE_FORGOT_PASSWORD: 24,
  STORE_DECLINED: 26,

  ORDER_PAYMENT_DONE: 40,
  ORDER_BOOKED: 41,
  ORDER_READY: 42,
  ORDER_DISPATCH: 43,
  ORDER_DIGITAL_CODE: 44,
  ORDER_REMAINING: 51,
  ORDER_DELIVERED: 52,

  USER_ORDER_COMPLETED: 45,
  USER_ORDER_CANCELLED: 47,
  PROVIDER_ORDER_CANCELLED: 53,
  NEW_ORDER: 55,
  STORE_ORDER_READY: 56,
  ORDER_ASSIGN: 57,
  STORE_ORDER_COMPLETED: 58,
  STORE_ORDER_CANCELLED: 59,
  USER_PAYMENT_REFUND: 74,
  STORE_PAYMENT_REFUND: 76,
  STORE_ORDER_PAYMENT_DONE: 77,

  DELIVERY_MAN_ACCEPTED: 60,
  DELIVERY_MAN_COMING: 61,
  DELIVERY_MAN_ARRIVED: 62,

  DELIVERY_MAN_STARTED_DELIVERY: 64,
  DELIVERY_MAN_REACHED_AT_DESTINATION: 65,

  DELIVERY_MAN_ON_THE_WAY: 48,
  DELIVERY_MAN_ARRIVED_AT_DESTINATION: 49,

  USER_ORDER_REJECTED: 50,
  USER_ORDER_PREPARE: 81,
};

exports = ADS_TYPE = {
  FOR_DELIVERY_LIST: 1,
  STORE_LIST: 2,
  FOR_INSIDE_STORE: 3,
};

exports = ID_FOR_ALL = {
  ALL_ID: "000000000000000000000000",
};

exports = ADMIN_DATA_ID = {
  ADMIN: 1,
  SUB_ADMIN: 3,
  STORE: 2,
  USER: 7,
  PROVIDER: 8,
  PROVIDER_VEHICLE: 9,
};

exports = PROMO_FOR_DELIVERY_SERVICE = {
  DELIVERY_SERVICE: 13,
};

exports = PUSH_NOTIFICATION_SOUND_FILE = {
  PUSH_NOTIFICATION_SOUND_FILE_IN_IOS: "default",
};
exports = IOS_PUSH_FILE_NAME = {
  // IOS_PROVIDER_CERT_FILE_NAME: 'provider_cert.pem',
  // IOS_PROVIDER_KEY_FILE_NAME: 'provider_key.pem',
  IOS_USER_CERT_FILE_NAME: "user_cert.pem",
  // IOS_USER_KEY_FILE_NAME: 'user_key.pem',
  // IOS_STORE_CERT_FILE_NAME: 'store_cert.pem',
  // IOS_STORE_KEY_FILE_NAME: 'store_key.pem',
  IOS_CERT_FILE_NAME: "push_file.p8",
};

exports = INVOICE_CODE = {
  INVOICE_APP_NAME_CODE: "ED",
  ORDER_EARNING_CODE: "OE",
  PROVIDER_WEEKLY_EARNING_CODE: "PWE",
  STORE_WEEKLY_EARNING_CODE: "SWE",
};
exports = UNIT = {
  DEGREE_TO_KM: 111,
  KM_TO_METER: 1000,
};

exports = ORDER_STATUS_ID = {
  IDEAL: 0,
  RUNNING: 1,
  CANCELLED: 2,
  REJECTED: 3,
  NO_ANSWER: 4,
  COMPLETED: 10,
};

exports = SEARCH_SORT = {
  NO_OF_RECORD_PER_PAGE: 10,
  NO_OF_RECORD_PER_PAGE_USER: 24,
  NO_OF_RECORD_PER_PAGE_STORE: 24,
  NO_OF_RECORD_PER_PAGE_CITY: 12,
  NO_OF_RECORD_PER_PAGE_OF_NO_ACTION: 13,
};
exports = ORDER_STATE = {
  WAITING_FOR_ACCEPT_STORE: 1,
  CANCELED_BY_USER: 101,
  ORDER_ON_HOLD: 102,
  STORE_ACCEPTED: 3,
  STORE_REJECTED: 103,
  STORE_CANCELLED: 104,
  STORE_CANCELLED_REQUEST: 105,
  STORE_PREPARING_ORDER: 5,
  ORDER_READY: 7,
  WAITING_FOR_DELIVERY_MAN: 9,
  NO_DELIVERY_MAN_FOUND: 109,
  NOT_ANSWERED: 110,
  DELIVERY_MAN_ACCEPTED: 11,
  DELIVERY_MAN_REJECTED: 111,
  DELIVERY_MAN_CANCELLED: 112,
  DELIVERY_MAN_COMING: 13,
  DELIVERY_MAN_ARRIVED: 15,
  DELIVERY_MAN_PICKED_ORDER: 17,
  DELIVERY_MAN_STARTED_DELIVERY: 19,
  DELIVERY_MAN_ARRIVED_AT_DESTINATION: 21,
  DELIVERY_MAN_COMPLETE_DELIVERY: 23,
  ORDER_COMPLETED: 25,
  ORDER_DELETED: 26,
  STORE_CREATE_ORDER: 998,
};
exports = PROVIDER_TYPE = {
  NORMAL: 1,
  OTHER: 2,
};
exports = PROVIDER_TYPE_STRING = {
  NORMAL_STRING: "Normal",
  OTHER_STRING: "Other",
};

exports = DEVICE_TYPE = {
  ANDROID: "android",
  IOS: "ios",
  WEB: "web",
};
exports = FILE_EXTENSION = {
  USER: ".jpg",
  PROVIDER: ".jpg",
  STORE: ".jpg",
  SERVICE: ".jpg",
  VEHICLE: ".jpg",
  DOCUMENT: ".jpg",
  PAYMENT: ".jpg",
  PRODUCT: ".jpg",
  ITEM: ".jpg",
  ADS: ".jpg",
  DELIVERY: ".jpg",
  LOGO: ".jpg",
  NOTIFICATIONS: ".jpg",
};
exports = FOLDER_NAME = {
  USER_PROFILES: 10,
  USER_DOCUMENTS: 11,
  PROVIDER_PROFILES: 20,
  PROVIDER_DOCUMENTS: 21,
  PROVIDER_VEHICLE_DOCUMENTS: 22,
  STORE_PROFILES: 30,
  STORE_DOCUMENTS: 31,
  STORE_PRODUCTS: 32,
  STORE_ITEMS: 33,
  CART_ITEMS: 34,
  DELIVERY_TYPE_IMAGES: 50,
  DELIVERY_ICON_IMAGES: 51,
  SERVICE_TYPE_IMAGES: 52,
  SERVICE_TYPE_MAP_PIN_IMAGES: 53,
  PAYMENT_IMAGES: 54,
  PAYMENT_SELECTED_IMAGES: 55,
  MAP_PIN_IMAGES: 56,
  EMAIL_IMAGES: 57,
  WEB_IMAGES: 58,
  DELIVERY_MAP_PIN_IMAGES: 59,
  ADS_MOBILE_IMAGES: 61,
  ADS_WEB_IMAGES: 62,
  ORDER_RECEIPT: 63,
  NOTIFICATIONS: 64,
};
exports = ADMIN_PROFIT_ON_ORDER = [
  { ID: 1, NAME: "PERCENTAGE" },
  { ID: 2, NAME: "PER ORDER" },
  { ID: 3, NAME: "PER ITEMS" },
];
// CONSTANTS
exports = ADMIN_PROFIT_ON_ORDER_ID = {
  PERCENTAGE: 1,
  PER_ORDER: 2,
  PER_ITEMS: 3,
};
exports = ADMIN_PROFIT_ON_ORDER_STRING = {
  PERCENTAGE: "Percentage",
  PER_ORDER: "Absolute price per order",
  PER_ITEMS: "Absolute price per item",
};
exports = ADMIN_PROFIT_ON_DELIVERY_ID = {
  PERCENTAGE: 1,
  PER_DELVIERY: 2,
};

exports = ADMIN_PROFIT_ON_DELIVERY_STRING = {
  PERCENTAGE: "Percentage",
  PER_DELVIERY: "Absolute price per delivery",
};
// CONSTANT ARRAY
exports = ADMIN_PROFIT_ON_ORDER = [
  {
    ID: ADMIN_PROFIT_ON_ORDER_ID.PERCENTAGE,
    NAME: ADMIN_PROFIT_ON_ORDER_STRING.PERCENTAGE,
  },
  {
    ID: ADMIN_PROFIT_ON_ORDER_ID.PER_ORDER,
    NAME: ADMIN_PROFIT_ON_ORDER_STRING.PER_ORDER,
  },
  {
    ID: ADMIN_PROFIT_ON_ORDER_ID.PER_ITEMS,
    NAME: ADMIN_PROFIT_ON_ORDER_STRING.PER_ITEMS,
  },
];
exports = ADMIN_PROFIT_ON_DELIVERY = [
  {
    ID: ADMIN_PROFIT_ON_DELIVERY_ID.PERCENTAGE,
    NAME: ADMIN_PROFIT_ON_DELIVERY_STRING.PERCENTAGE,
  },
  {
    ID: ADMIN_PROFIT_ON_DELIVERY_ID.PER_DELVIERY,
    NAME: ADMIN_PROFIT_ON_DELIVERY_STRING.PER_DELVIERY,
  },
];

exports = WALLET_STATUS_ID = {
  ADD_WALLET_AMOUNT: 1,
  REMOVE_WALLET_AMOUNT: 2,
};

exports = WALLET_COMMENT_ID = {
  SET_BY_ADMIN: 1,
  ADDED_BY_CARD: 2,
  ADDED_BY_REFERRAL: 3,
  ORDER_CHARGED: 4,
  ORDER_REFUND: 5,
  SET_ORDER_PROFIT: 6,
  ORDER_CANCELLATION_CHARGE: 7,
  SET_BY_WALLET_REQUEST: 8,

  SET_WEEKLY_PAYMENT_BY_ADMIN: 9,
};

//exports = WALLET_COMMENT_ID = {
//    ADDED_BY_ADMIN: 1,
//    ADDED_BY_CARD: 2,
//    ADDED_BY_REFERRAL: 3,
//    ORDER_CHARGED: 4,
//    ORDER_REFUND: 5,
//    ORDER_PROFIT: 6,
//    ORDER_CANCELLATION_CHARGE: 7,
//    WALLET_REQUEST_CHARGE: 8,
//};
exports = WALLET_COMMENT_ID_STRING = {
  ADDED_BY_ADMIN: "ADDED_BY_ADMIN",
  ADDED_BY_CARD: "ADDED_BY_CARD",
  ADDED_BY_REFERRAL: "ADDED_BY_REFERRAL",
  ORDER_CHARGED: "ORDER_CHARGED",
  ORDER_REFUND: "ORDER_REFUND",
  ORDER_PROFIT: "ORDER_PROFIT",
  ORDER_CANCELLATION_CHARGE: "ORDER_CANCELLATION_CHARGE",
  WALLET_REQUEST_CHARGE: "WALLET_REQUEST_CHARGE",
};

exports = WALLET_COMMENT = [
  {
    ID: WALLET_COMMENT_ID.ADDED_BY_ADMIN,
    NAME: WALLET_COMMENT_ID_STRING.ADDED_BY_ADMIN,
  },
  {
    ID: WALLET_COMMENT_ID.ADDED_BY_CARD,
    NAME: WALLET_COMMENT_ID_STRING.ADDED_BY_CARD,
  },
  {
    ID: WALLET_COMMENT_ID.ADDED_BY_REFERRAL,
    NAME: WALLET_COMMENT_ID_STRING.ADDED_BY_REFERRAL,
  },
  {
    ID: WALLET_COMMENT_ID.ORDER_CHARGED,
    NAME: WALLET_COMMENT_ID_STRING.ORDER_CHARGED,
  },
  {
    ID: WALLET_COMMENT_ID.ORDER_REFUND,
    NAME: WALLET_COMMENT_ID_STRING.ORDER_REFUND,
  },
  {
    ID: WALLET_COMMENT_ID.ORDER_PROFIT,
    NAME: WALLET_COMMENT_ID_STRING.ORDER_PROFIT,
  },
  {
    ID: WALLET_COMMENT_ID.ORDER_CANCELLATION_CHARGE,
    NAME: WALLET_COMMENT_ID_STRING.ORDER_CANCELLATION_CHARGE,
  },
];

exports = WALLET_REQUEST_STATUS = {
  CREATED: 1,
  ACCEPTED: 2,
  TRANSFERED: 3,
  COMPLETED: 4,
  CANCELLED: 5,
};

// ORDER_CANCELLATION_CHARGE CONSTANT
exports = ORDER_CANCELLATION_CHARGE_TYPE = {
  PERCENTAGE: 1,
  ABSOLUTE: 2,
};
exports = ORDER_CANCELLATION_CHARGE_TYPE_STRING = {
  PERCENTAGE: "Percentage",
  ABSOLUTE: "Absolute",
};

// ORDER_CANCELLATION_CHARGE CONSTANT ARRAY
exports = ORDER_CANCELLATION_CHARGE = [
  {
    ID: ORDER_CANCELLATION_CHARGE_TYPE.PERCENTAGE,
    NAME: ORDER_CANCELLATION_CHARGE_TYPE_STRING.PERCENTAGE,
  },
  {
    ID: ORDER_CANCELLATION_CHARGE_TYPE.ABSOLUTE,
    NAME: ORDER_CANCELLATION_CHARGE_TYPE_STRING.ABSOLUTE,
  },
];

exports = TAG = {
  DAY: "DAY",
  WEEK: "WEEK",
};

exports = PROMO_RECURSION_ID = {
  NO_RECURSION: 0,
  DAILY_RECURSION: 1,
  WEEKLY_RECURSION: 2,
  MONTHLY_RECURSION: 3,
  ANNUALLY_RECURSION: 4,
};

exports = WEEK = {
  1: "First",
  2: "Second",
  3: "Third",
  4: "Fourth",
  5: "Fifth",
};

exports = DAY = {
  0: "Sunday",
  1: "Monday",
  2: "Tuesday",
  3: "Wednesday",
  4: "Thursday",
  5: "Friday",
  6: "Saturday",
};

exports = MONTH = {
  0: "January",
  1: "February",
  2: "March",
  3: "April",
  4: "May",
  5: "June",
  6: "July",
  7: "August",
  8: "September",
  9: "October",
  10: "November",
  11: "December",
};

exports = PROMO_FOR = {
  SERVICE: 20,
  DELIVERIES: 0,
  STORE: 2,
  PRODUCT: 21,
  ITEM: 22,
};
