exports = MESSAGE_CODE = {
  DETAIL_VALID: 5000,
  PASSWORD_SET_SUCESSFULLY: 5001,
};
exports = USER_MESSAGE_CODE = {
  REGISTER_SUCCESSFULLY: 101,
  REMOVED_SUCCESSFULLY: 5001,
  LOGIN_SUCCESSFULLY: 102,
  UPDATE_SUCCESSFULLY: 103,
  PASSWORD_RESET_SUCCESSFULLY: 104,
  GET_OTP_SUCCESSFULLY: 105,
  DEVICE_TOKEN_UPDATE_SUCCESSFULLY: 106,
  LOGOUT_SUCCESSFULLY: 107,
  SKIPPED_REFERRAL_PROCESS: 111,
  REFERRAL_PROCESS_COMPLETED_SUCCESSFULLY: 112,
  FARE_ESTIMATE_SUCCESSFULLY: 113,
  WALLET_AMOUNT_ADD_SUCCESSFULLY: 114,
  CHANGE_WALLET_STATUS_SUCCESSFULLY: 115,
  ORDER_PAYMENT_SUCCESSFULLY: 116,
  ORDER_HISTORY_SUCCESSFULLY: 117,
  GET_PROVIDER_LOCATION_SUCCESSFULLY: 118,
  USER_LIST_SUCCESSFULLY: 119,
  GET_USER_ORDER_DETAIL_SUCCESSFULLY: 120,
  ADD_FAVOURITE_STORE_SUCCESSFULLY: 109,
  DELETE_FAVOURITE_STORE_SUCCESSFULLY: 110,
  SEND_SMS_SUCCESSFULLY: 108,
  SEND_NOTIFICATION_SUCCESSFULLY: 109,
  FAVOURITE_ADDRESS_ADDED_SUCCESSFULLY: 3000,
  FAVOURITE_ADDRESS_UPDATED_SUCCESSFULLY: 3001,

  APPROVED_SUCCESSFULLY: 191,
  DECLINED_SUCCESSFULLY: 192,
  GIVE_RATING_TO_PROVIDER_SUCCESSFULLY: 193,
  VALID_REFERRAL_CODE: 194,
  GET_DETAIL_SUCCESSFULLY: 195,
  OTP_VERIFICATION_SUCCESSFULLY: 196,
  PROMO_APPLY_SUCCESSFULLY: 197,
  GET_INVOICE_SUCCESSFULLY: 198,
  GIVE_RATING_TO_STORE_SUCCESSFULLY: 199,
  GET_FAVOURITE_STORE_LIST_SUCCESSFULLY: 200,
  GET_STORE_REVIEW_LIST_SUCCESSFULLY: 306,
  REVIEW_COMMENT_SUCCESSFULLY: 307,
  GET_STORE_LIST_SUCCESSFULLY: 308,
};

exports = CATEGORY_MESSAGE_CODE = {
  CATEGORY_ADD_SUCCESSFULLY: 385,
  CATEGORY_LIST_SUCCESSFULLY: 386,
  UPDATE_CATEGORY_SUCCESSFULLY: 387,
  GET_CATEGORY_PRODUCT_LIST: 388,
};

exports = STORE_MESSAGE_CODE = {
  REGISTER_SUCCESSFULLY: 121,
  LOGIN_SUCCESSFULLY: 122,
  UPDATE_SUCCESSFULLY: 123,
  PASSWORD_RESET_SUCCESSFULLY: 124,
  GET_OTP_SUCCESSFULLY: 125,
  DEVICE_TOKEN_UPDATE_SUCCESSFULLY: 126,
  LOGOUT_SUCCESSFULLY: 127,
  SKIPPED_REFERRAL_PROCESS: 131,
  REFERRAL_PROCESS_COMPLETED_SUCCESSFULLY: 132,
  STORE_DATA_SUCCESSFULLY: 133,
  STORE_LIST_SUCCESSFULLY: 134,
  ORDER_HISTORY_SUCCESSFULLY: 135,
  GET_STORE_ORDER_DETAIL_SUCCESSFULLY: 136,
  APPROVED_SUCCESSFULLY: 137,
  DECLINED_SUCCESSFULLY: 138,
  GET_DETAIL_SUCCESSFULLY: 139,
  OTP_VERIFICATION_SUCCESSFULLY: 140,
  PAY_BY_CASH_ON_DELIVERY_SUCCESSFULLY: 141,
  GIVE_RATING_TO_USER_SUCCESSFULLY: 142,
  GIVE_RATING_TO_PROVIDER_SUCCESSFULLY: 143,
  GET_DAILY_EARNING_SUCCESSFULLY: 144,
  GET_WEEKLY_EARNING_SUCCESSFULLY: 145,
  CANCEL_REQUEST_SUCESSFULLY: 146,
  STORE_PAY_ORDER_PAYMENT: 147,
  CREATE_ORDER_SUCCESSFULLY: 148,
  STORE_GET_INVOICE_SUCCESSFULLY: 149,
  STORE_ORDER_UPDATE_SUCCESSFULLY: 150,
};

exports = PROVIDER_MESSAGE_CODE = {
  REGISTER_SUCCESSFULLY: 201,
  LOGIN_SUCCESSFULLY: 202,
  UPDATE_SUCCESSFULLY: 203,
  PASSWORD_RESET_SUCCESSFULLY: 204,
  GET_OTP_SUCCESSFULLY: 205,
  DEVICE_TOKEN_UPDATE_SUCCESSFULLY: 206,
  LOGOUT_SUCCESSFULLY: 207,
  STATUS_CHANGED_SUCCESSFULLY: 208,
  PROVIDER_LIST_SUCCESSFULLY: 209,
  LOCATION_UPDATE_SUCCESSFULLY: 210,
  PROVIDER_DETAIL_SUCCESSFULLY: 211,
  ORDER_HISTORY_SUCCESSFULLY: 212,
  GET_PROVIDER_ORDER_DETAIL_SUCCESSFULLY: 213,
  APPROVED_SUCCESSFULLY: 214,
  DECLINED_SUCCESSFULLY: 215,
  GIVE_RATING_TO_USER_SUCCESSFULLY: 216,
  GET_DETAIL_SUCCESSFULLY: 217,
  OTP_VERIFICATION_SUCCESSFULLY: 218,
  GET_DAILY_EARNING_SUCCESSFULLY: 219,
  GET_WEEKLY_EARNING_SUCCESSFULLY: 220,
  GIVE_RATING_TO_STORE_SUCCESSFULLY: 221,

  PROVIDER_VEHICLE_ADD_SUCCESSFULLY: 222,
  PROVIDER_VEHICLE_UPDATE_SUCCESSFULLY: 223,
  PROVIDER_VEHICLE_LIST_SUCCESSFULLY: 224,
  GET_REQUEST_COUNT_SUCCESSFULLY: 225,
};

exports = ORDER_MESSAGE_CODE = {
  ORDER_CREATE_SUCCESSFULLY: 241,
  ORDER_LIST_SUCCESSFULLY: 242,
  SET_ORDER_STATUS_SUCCESSFULLY: 243,
  REQUEST_CREATE_SUCCESSFULLY: 244,
  CHANGE_ORDER_STATUS_SUCCESSFULLY: 245,
  ORDER_CANCEL_SUCCESSFULLY: 246,
  ORDER_CANCEL_OR_REJECT_BY_PROVIDER_SUCCESSFULLY: 247,
  ORDER_CANCEL_OR_REJECT_BY_STORE_SUCCESSFULLY: 248,
  GET_ORDER_DATA_SUCCESSFULLY: 249,
  ORDER_LIST_FOR_DELIVERY_SUCCESSFULLY: 250,
  ORDER_LIST_FOR_PROVIDER_SUCCESSFULLY: 251,
  ORDER_LIST_FOR_USER_SUCCESSFULLY: 252,
  ORDER_COMPLETED_SUCCESSFULLY: 253,
  GET_ORDER_STATUS_SUCCESSFULLY: 254,
  USER_GET_ORDER_STATUS_SUCCESSFULLY: 255,
  SHOW_INVOICE_SUCCESSFULLY: 256,
  GET_REQUEST_STATUS_SUCCESSFULLY: 257,
};

exports = CART_MESSAGE_CODE = {
  CART_UPDATED_SUCCESSFULLY: 951,
  CART_ADDED_SUCCESSFULLY: 952,
  CART_GET_SUCCESSFULLY: 953,
  CART_DELETE_SUCCESSFULLY: 954,
  DESTINATION_CHANGE_SUCCESSFULLY: 955,
};

exports = COUNTRY_MESSAGE_CODE = {
  COUNTRY_LIST_SUCCESSFULLY: 301,
  ADD_COUNTRY_SUCCESSFULLY: 302,
  UPDATE_SUCCESSFULLY: 303,
};

exports = CITY_MESSAGE_CODE = {
  CITY_LIST_SUCCESSFULLY: 311,
  ADD_CITY_SUCCESSFULLY: 312,
  UPDATE_SUCCESSFULLY: 313,
};

exports = WALLET_REQUEST_MESSAGE_CODE = {
  WALLET_REQUEST_CREATE_SUCCESSFULLY: 314,
  WALLET_REQUEST_GET_SUCCESSFULLY: 315,
  WALLET_REQUEST_COMPLETED_SUCCESSFULLY: 316,
  WALLET_REQUEST_CANCELLED_SUCCESSFULLY: 317,
  WALLET_REQUEST_TRANSFERED_SUCCESSFULLY: 318,
  WALLET_REQUEST_ACCEPTED_SUCCESSFULLY: 319,
  WALLET_HISTORY_GET_SUCCESSFULLY: 320,
};

exports = SETTING_MESSAGE_CODE = {
  APP_KEY_LIST_SUCCESSFULLY: 321,
  SETTING_DETAIL_LIST_SUCCESSFULLY: 331,
  SETTING_UPDATE_SUCCESSFULLY: 2061,
};

exports = DELIVERY_MESSAGE_CODE = {
  DELIVERY_LIST_SUCCESSFULLY: 341,
  DELIVERY_DATA_ADD_SUCCESSFULLY: 342,
  DELIVERY_LIST_FOR_CITY_SUCCESSFULLY: 343,
  DELIVERY_LIST_FOR_NEAREST_CITY_SUCCESSFULLY: 344,
  UPDATE_SUCCESSFULLY: 345,
};

exports = VEHICLE_MESSAGE_CODE = {
  VEHICLE_LIST_SUCCESSFULLY: 351,
  VEHICLE_DATA_ADD_SUCCESSFULLY: 352,
  UPDATE_SUCCESSFULLY: 353,
};

exports = PAYMENT_GATEWAY_MESSAGE_CODE = {
  PAYMENT_GATEWAY_DATA_ADD_SUCCESSFULLY: 361,
  LIST_SUCCESSFULLY: 362,
  UPDATE_SUCCESSFULLY: 363,
};

exports = ADMIN_MESSAGE_CODE = {
  ADD_SUCCESSFULLY: 981,
  UPDATE_SUCCESSFULLY: 982,
  LIST_SUCCESSFULLY: 983,
  GET_DETAIL_SUCCESSFULLY: 984,
  DELETE_SUCCESSFULLY: 985,
  LOGIN_SUCCESSFULLY: 986,
};

exports = SERVICE_MESSAGE_CODE = {
  SERVICE_ADD_SUCCESSFULLY: 371,
  SERVICE_LIST_SUCCESSFULLY: 372,
  UPDATE_SUCCESSFULLY: 373,
};

exports = PRODUCT_MESSAGE_CODE = {
  PRODUCT_ADD_SUCCESSFULLY: 381,
  PRODUCT_LIST_SUCCESSFULLY: 382,
  UPDATE_SUCCESSFULLY: 383,
  GET_PRODUCT_ITEM_LIST: 384,
  DELETE_SUCCESSFULLY: 385,
};

exports = SPECIFICATION_MESSAGE_CODE = {
  SPECIFICATION_ADD_SUCCESSFULLY: 391,
  SPECIFICATION_LIST_SUCCESSFULLY: 392,
  SPECIFICATION_DELETE_SUCCESSFULLY: 393,
};

exports = ITEM_MESSAGE_CODE = {
  ITEM_ADD_SUCCESSFULLY: 901,
  ITEM_IMAGE_UPLOAD_SUCCESSFULLY: 902,
  ITEM_IMAGE_UPDATE_SUCCESSFULLY: 903,
  ITEM_LIST_SUCCESSFULLY: 904,
  UPDATE_SUCCESSFULLY: 905,
  ITEM_STATE_CHANGE_SUCCESSFULLY: 906,

  ITEM_SUBSTITUTE_SUCCESSFULLY: 907,
  DELETE_SUCCESSFULLY: 908,
  ITEM_SUBSTITUTE_ALREADY_EXIST: 2015,
};

exports = CART_CHECKOUT_CODE = {
  ORDER_PAYMENT_NOT_FOUND: 2017,
  INVALID_PAYMENT_TOKEN: 2018,
  ADD_CARD_FAILED: 2019,
  GET_CARD_LIST_FAILED: 2020,
  INVALID_CARD_DETAILS: 2021,
};

exports = DOCUMENT_MESSAGE_CODE = {
  DOCUMENT_ADD_SUCCESSFULLY: 911,
  DOCUMENT_LIST_SUCCESSFULLY: 912,
  DOCUMENT_IMAGE_UPLOAD_SUCCESSFULLY: 913,
  UPDATE_SUCCESSFULLY: 914,
};

exports = PROMO_CODE_MESSAGE_CODE = {
  PROMO_CODE_ADD_SUCCESSFULLY: 921,
  PROMO_CODE_LIST_SUCCESSFULLY: 922,
  UPDATE_SUCCESSFULLY: 923,
};

exports = CARD_MESSAGE_CODE = {
  CARD_ADD_SUCCESSFULLY: 924,
  CARD_LIST_SUCCESSFULLY: 925,
  CARD_DELETE_SUCCESSFULLY: 926,
  CARD_SELECTED_SUCCESSFULLY: 927,
  CARD_DESELECT_SUCCESSFULLY: 928,
};

exports = BANK_DETAIL_MESSAGE_CODE = {
  BANK_DETAIL_ADD_SUCCESSFULLY: 2001,
  BANK_DETAIL_LIST_SUCCESSFULLY: 2002,
  BANK_DETAIL_UPDATE_SUCCESSFULLY: 2003,
  BANK_DETAIL_DELETE_SUCCESSFULLY: 2004,
  BANK_DETAIL_SELECT_SUCCESSFULLY: 2003,
};

exports = ADS_MESSAGE_CODE = {
  ADS_ADD_SUCCESSFULLY: 915,
  ADS_LIST_GET_SUCCESSFULLY: 916,
  ADS_UPDATE_SUCCESSFULLY: 917,
  ADS_DELETE_SUCCESSFULLY: 918,
};

exports = SPECIFICATION_GROUP_MESSAGE_CODE = {
  ADD_SUCCESSFULLY: 2041,
  LIST_SUCCESSFULLY: 2042,
};

exports = SMS_MESSAGE_CODE = {
  GET_SMS_LIST_SUCCESSFULLY: 2051,
  GET_SMS_DETAIL_SUCCESSFULLY: 2052,
  SMS_UPDATE_SUCCESSFULLY: 2053,
  SMS_CONFIG_UPDATE_SUCCESSFULLY: 2054,
};

exports = EMAIL_MESSAGE_CODE = {
  GET_EMAIL_LIST_SUCCESSFULLY: 2011,
  GET_EMAIL_DETAIL_SUCCESSFULLY: 2012,
  EMAIL_UPDATE_SUCCESSFULLY: 2013,
  EMAIL_CONFIG_UPDATE_SUCCESSFULLY: 2014,
};
