export var menu_title = {
  create_order: 'Create Order',
  upload_document: 'Upload Document',
  order: 'Orders',
  deliveries: 'Deliveries',
  history: 'History',
  product: 'Product',
  item: 'Item',
  setting: 'Setting',
  store: 'Stores',
  earning: 'Earning',
  sub_earning: 'Earning',
  sub_daily_earning: 'Daily Earning',
  sub_weekly_earning: 'Weekly Earning',
  profile: 'Profile',
  logout: 'Logout',
  promocode: 'Promo code',
  providers: 'Providers',
};

export var title = {
  ///////////////for Franchise Register //////////////////////////
  store_item_tax: 'Item Tax',
  price_rating: 'Price Rating',
  rate: 'Rate',
  free_delivery_for_above_order_price: 'Free Delivery Above Price',
  delivery_time: 'Delivery Time',
  is_store_pay_delivery_fees: 'Store Pay Delivery Fee',
  is_business_store: 'Business',
  is_document_uploaded: 'Document Uploaded',
  language: 'Language',
  content: 'Write SMS Content',
  notification_content: 'Write Notification Content',
  name: 'Name',
  email: 'Email',
  password: 'Password',
  confirm_password: 'Confirm Password',
  website_url: 'Website Url',
  slogan: 'Slogan',
  select_country: 'Select Country',
  select_city: 'Select City',
  address: 'Address',
  country_phone_code: 'Phone Code',
  phone: 'Phone Number',
  fax_number: 'Fax Number',
  select_delivery: 'Selct Delivery Type',
  latitude: 'Latitude',
  longitude: 'Longitude',
  famous_for: 'Famous For',
  image_url: 'Image',
  store: 'Store',
  referral_code: 'Referral Code',
  message_602: 'done',
  is_required: 'Required',

  register_your_account: 'Register Your Account',
  confirmation_code: 'Confirmation Code',
  sms_otp: 'Sms Verification Code',
  email_otp: 'Email Verification Code',
  verification: 'Verification',
  spec: 'Spec.',
  promo_expiry_date: 'Expiry Date',
  product: 'Product',

  invalid_amount:
    'The configuration allows you to specify a minimum\n' +
    '      amount,that order totals are required to meet',

  details: 'Detail',
  is_visible_in_store: 'Visible In Franchise',
  is_item_in_stock: 'Item In Stock',
  email_or_phone: 'Email Or Phone',
  for_use: 'For Use',
  item: 'Item',
  price: 'Price',
  is_default_selected: 'Default Selected',
  is_user_selected: 'User Selected',
  specifications: 'Specifications',
  item_note_here: 'Item Note Here',

  new_password: 'New Password',
  old_password: 'Old Password',
  country: 'Country',
  city: 'City',
  total_referrals: 'Total Referrals',
  referred_by: 'Referred By',
  setting: 'Setting',
  admin_profit_mode: 'Admin Profit Mode',
  admin_profit_value: 'Admin Profit Value',
  phone_number_verified: 'Phone Number Verified',
  email_verified: 'Email Verified',
  approved: 'Approved',
  prov_city: 'City',
  delivery_type: 'Delivery Type',
  personal_detail: 'Personal Detail',
  store_name: 'Personal Detail',
  app_version: 'App Version',
  currency_code: 'Currency Code',
  wallet: 'Wallet',
  referral: 'Referral',
  item_name: 'Item Name',

  is_default: 'Visible',
  is_in_stock: 'In Stock',
  is_most_popular: 'Most Popular',
  specification_name: 'Name',
  specification_type: 'Type',
  specification_detail: 'Detail',
  action: 'Action',
  item_specification_name: 'Item Specification Name',
  select_type: 'Select Type',
  add_specification: 'Add Specification',
  default_select: 'Default Select',
  user_selected: 'User Select',
  type_single: 'Single',
  type_multiple: 'Multiple',

  error_atleast_one_specification: 'Select Atleast One Specification',

  item_tax: 'Item Tax',
  is_visible: 'Visible',
  is_busy: 'Busy',
  store_open_time: 'Franchise Open Time',
  store_close_time: 'Franchise Close Time',
  free_delivery_within_radius: 'Free Delivery Within Radius',

  completed: 'Completed',
  remaining: 'Remaining',

  manual: 'manual',
  social: 'social',

  id: 'Id',
  user: 'User',
  provider: 'Provider',
  payment_by: 'Payment By',
  total: 'Total',
  unique_id_for_store_data: 'unique_id_for_store_data',
  status: 'Status',
  card: 'Card',
  cash: 'Cash',
  user_rating: 'User Rating',
  provider_rating: 'Provider Rating',

  product_name: 'Product Name',
  date_time: 'Date & Time',
  date: 'Date',

  sort: 'Sort',
  search: 'Search',
  date_filter: 'Date Filter',
  ascending: 'Ascending',
  descending: 'Descending',
  filter_id: 'Id',
  filter_name: 'Name',
  value: 'Value',
  expiry_date: 'Expiry Date',
  filter_user: 'User',
  filter_provider: 'Provider',
  filter_item: 'Item',
  filter_product: 'Product',

  please_contact_to_admin: 'Please Contact To Admin',

  order: 'Order',
  service_fees: 'Service Fees',
  order_fees: 'Order Fees',
  store_profit: 'Franchise Profit',
  paid_service_fee: 'Paid Service Fee',
  recieved_order_payment: 'Recieved Order Payment',
  earning: 'Earning',
  currency: 'Currency',
  admin_earning: 'Admin Earning',
  provider_earning: 'Provider Earning',
  pay_to_provider: 'Pay To Provider',
  pay_store: 'Pay Franchise',

  completed_order: 'Completed Order',
  order_amount: 'Order Amount',
  pay_by_admin: 'Pay By Admin',

  ////////// daily earning ///////
  item_price: 'Item Price',
  total_order_price: 'Order Price',
  deduct_from_wallet: 'Deduct from wallet',
  added_in_wallet: 'Added in wallet',
  admin_profit: 'Admin Profit',
  total_earnings: 'Total Earnings',
  paid_in_wallet: 'PAID IN WALLET',
  paid: 'PAID',
  remaining_to_pay: 'REMAINING TO PAY',
  received_order_amount: 'Received Order Amount',
  pay_to_store: 'Pay To Franchise',

  payment_status: 'Payment Status',
  no_of_item: 'No Of Item',
  total_cart_price: 'Total Cart Price',
  store_have_service_payment: 'Franchise Service Payment',
  total_store_income: 'Total Franchise Income',
  total_order: 'Total Order',
  accepted_order: 'Accepted Order',
  cancelled_order: 'Cancelled Order',

  referral_credit: 'Referral Credit',
  total_referred: 'Total Referred',

  all: 'All',
  yes: 'YES',
  no: 'NO',

  doesnot_have_an_account: "Doesn't have an account?",
  store_title1: 'Welcome to',
  store_title2: 'YeePeey Franchise Panel',
  signin_to_your_account: 'Sign in to your account',
  forgot_password: 'Forgot Password',

  offer: 'Offer',
  comment: 'Comment',
  unique_code: 'Unique Code',
  exp_date: 'Exp. Date',

  order_payment_paid_by_store: 'Order Paymnet paid by Franchise?',
  vehicle: 'Vehicle',

  ////////

  created_at: 'Created At',
  store_accepted_at: 'Franchise Accepted At',
  preparing_order_at: 'Preparing Order At',
  order_ready_at: 'Order Ready At',
  store_order_send_at: 'Franchise Order Send At',
  provider_accepted_at: 'Provider Accepted At',
  completed_at: 'Completed At',
  delivered_at: 'Delivered At',
  start_for_delivery_at: 'Start For Delivery At',
  picked_order_at: 'Picked Order At',
  arrived_on_store_at: 'Arrived On Franchise At',
  start_for_pickup_at: 'Start for Pickup At',

  //////////////////////////
  base_price: 'Base Price',
  distance_price: 'Distance Price',
  time_price: 'Time Price',
  service_price: 'Service Payment',
  tax_price: 'Tax Price',
  surge_price: 'Surge Price',
  total_delivery_price: 'DELIVERY PRICE',
  promo_bonus: 'Promo Bonus',

  cart_price: 'Cart Price',

  order_payment: 'Order Payment',
  delivery_payment: 'Delivery Payment',

  ///////////

  wallet_payment: 'Wallet Payment',
  cash_payment: 'Cash Payment',
  other_payment: 'Other Payment',
  user_payment: 'User Payment',

  profit: 'Profit',
  items: 'items',
  qty: 'Qty.',
  order_completed: 'ORDER COMPLETED',

  already_account: 'Already have an account?',
  open_full_time: 'Open Full Time',
  open: 'Open',
  sunday: 'Sun',
  monday: 'Mon',
  tuesday: 'Tue',
  wednesday: 'Wed',
  thursday: 'Thu',
  friday: 'Fri',
  saturday: 'Sat',
  required: 'Required',
  add_item_note: 'Add Item Note',

  mobile_no: 'Mobile No.',
  total_service_cost: 'Total Service Cost',
  specification_price: 'Specification Price',
  total_item_cost: 'Total Item Cost',

  first_name: 'First Name',
  last_name: 'Last Name',
  enter_first_name: 'Enter First Name',
  enter_last_name: 'Enter Last Name',
  enter_email: 'Enter Email',
  enter_mobile_no: 'Enter Mobile No.',

  order_cancellation_charge_for_above_order_price:
    'Order Cancellation Charge Above Price',
  is_order_cancellation_charge_apply: 'Order Cancellation Charge',
  order_cancellation_charge_type: 'Order Cancellation Charge Type',
  order_cancellation_charge_value: 'Order Cancellation Charge Value',
  max_item_quantity_add_by_user: 'Maximum Item Quantity Add By User',
  schedule_order_create_after_minute: 'Schedule Order Create After Minute',
  is_provider_delivery_anywhere: 'Provider Delivery Anywhere',
  delivery_radius: 'Delivery Radius',
  is_taking_schedule_order: 'Taking Schedule Order',
  inform_schedule_order_before_min: 'Inform Schedule Order Before Minute',
  min_order_price: 'Minimum Order Price',
  percentage: 'Percentage',
  absolute: 'Absolute',

  item_image_size_error: 'Image Size Not Proper',
  item_image_ratio_error: 'Image Ratio Not Proper',
  item_image_extension_error: 'Image Extension Not Proper',

  cancel_reason1: 'Order item outof stock',
  cancel_reason2: 'Delivery Adress not reachable',

  promo_code_name: 'Name',
  promo_code_type: 'Type',
  promo_code_value: 'Value',
  order_or_service: 'Order/Service',
  uses: 'Uses',
  user_used: 'User Used',
  state: 'State',
  promo_is_expired: 'Is Expired',
  promo_apply_on: 'Promo Apply On',
  is_active: 'Active',
  is_approved: 'Approved',
  is_promo_required_uses: 'Required Uses',
  is_promo_expiry_date: 'Expiry',
  is_promo_have_minimum_amount_limit: 'Minimum Amount Limit',
  is_promo_have_max_discount_limit: 'Maximum Discount Limit',
  promo_code_uses: 'no Of User to use',
  code_expiry: 'Expiry Date',
  promo_code_apply_on_minimum_amount: 'Minimum Amount Limit',
  promo_code_max_discount_amount: 'Maximum Discount',
  start_date: 'Start Date',
  admin_loyalty: 'Admin Loyality',
  promo_created_loyalty: 'Promo Created Loyality',
  promo_for: 'Promo For',
  admin_loyalty_type: 'Admin Louality Type',
};

export var button = {
  view_detail: 'View Detail',
  edit_detail: 'Edit Detail',
  history: 'History',
  decline: 'Decline',
  approved: 'Aecline',
  send_notification: 'Send Notification',
  view_document: 'View Document',
  submit: 'Submit',
  register: 'Register',
  login: 'Login',
  login_button: 'LOGIN',
  close: 'Close',
  update: 'Update',
  add_item: 'Add Item',
  add_store: 'Add Store',
  add_specification: 'Add Specification',
  add_product: 'Add Product',
  add: 'Add',
  save: 'Save',
  send: 'Send',
  edit: 'Edit',
  delete: 'Delete',
  unavailable: 'unavailable',
  remove: 'Remove',
  change: 'Change',
  select_file: 'Select File',
  add_store_time: 'Add Time',
  update_item: 'Update Item',
  view_specification: 'View Specification',
  view_full_invoice: 'View Full Invoice',

  accept: 'Accept',
  resject: 'Reject',
  prepare_for_order: 'Prepare For Order',
  order_ready: 'Order Ready',
  assign_delivery_for_provider: 'Assign Delivery For Provider',
  reassign_delivery_for_provider: 'Re Assign Delivery For Provider',
  cancle: 'Cancel',
  cancel_request: 'Cancel Request',
  reject: 'Reject',
  view_order_detail: 'View Order Detail',
  view_cart_detail: 'View Cart Detail',
  track_delivery_man: 'Track Delivery Man',
  pre: 'Pre',
  next: 'Next',
  get_confirmation_code: 'Get Confirmation Code',
  apply: 'Apply',
  export_excel: 'Export',
  price_paid_by_store: 'Price Paid By Franchise',
  ok: 'Ok',

  register_now: 'REGISTER NOW',
  forgot_password: 'Forgot password?',
  sign_up: 'SIGN UP',
  to: 'To',

  add_to_cart: 'Add To Cart',
  cart: 'CART',
  checkout: 'CHECKOUT',
  clear_all: 'clear all',
  place_order: 'Place Order',
  quick_delivery: 'Quick Delivery',
  confirmation_code: 'Confirmation Code',
  complete_order: 'Complete Order',
  inActive: 'Inactive',
  active: 'Active',
  add_promo: 'Add Promo Code',
};
export var status = {
  created: 'Created',
  waiting_for_accept: 'Waiting for Accept',
  accepted: 'Accepted',
  start_preparing_order: 'Start Preparing order',
  order_ready: 'Order Ready',
  waiting_for_delivery_man: 'Waiting for Delivery Man',
  delivery_man_accepted: 'Delivery Man Accepted',
  delivery_man_coming: 'Delivery Man Coming',
  delivery_man_arrived: 'Delivery Man Arrived',
  picked_order: 'Delivery Man Picked Order ',
  started_for_delivery: 'Started For Delivery',
  arrived_at_destination: 'Delivery Man Arrived at Destination',
  delivered_ordered: 'Delivered Order',
  assign_order_to_Delivery_man: 'Order Assign To Delivery Man',
  rejected: 'Rejected',
  cancelled: 'Cancelled',
  no_delivery_man_found: 'No Delivery Man Found',
  delivery_man_rejected: 'Delivery Man Rejected',
  delivery_man_cancelled: 'Cancle By Delivery Man',
  user_cancelled: 'Cancle By User',
  oredr_complete: 'Order Complete',
  order_delivered: 'Order Delivered',
  completed: 'Completed',
  not_completed: 'Not Completed',
  cancelled_request: 'Request Cancelled',
};

export var message = {
  specification_already_added: 'Specification Already Added',
  item_already_exist: 'Item Already Exist In this Product',
  product_already_exist: 'Product Already Exist',
};

export var heading_title = {
  admin_sms: 'Send SMS',
  admin_send_notification: 'Send Notification',
  complete_order: 'Complete Order',
  product_title: 'Product Data',
  specification_list: 'Specification list',
  item_title: 'Item Data',
  item_setting: 'Item Setting',
  item_specification: 'Item Specification',
  add_item_specification: 'Add Item Specification',
  store_setting_title: 'Franchise Setting',
  add_store_time: 'Add Franchise Time',
  store_time: 'Franchise Time',
  history: 'History',
  order_list: 'Order List',
  setting: 'Setting',
  delivery_list: 'Delivery List',
  item_images: 'Item Images',
  total_earning: 'Total Earning',
  order_earning: 'Order Earning',
  store_transactions: 'Franchise Transactions',
  other_earning: 'Other Earning',
  orders: 'Orders',
  order_user_detail: 'Order User Detail',

  you_are_decline: 'You Are Decline',
  rating: 'Rating',

  total_order: 'Total Order',
  accepted_order: 'Accepted Order',
  rejected_order: 'Rejected Order',
  completed_order: 'Completed Order',
  total_item_sold: 'Total Item Sold',
  accepted_ratio: 'Accepted Ratio',
  rejected_ratio: 'Rejected Ratio',
  completed_ratio: 'Completed Ratio',
  daily_earning: 'Daily Earning',
  payment: 'Payment',

  invoice_no: 'Invoice No.',
  user_detail: 'User Detail',
  provider_detail: 'Provider Detail',
  order_detail: 'Order Detail',
  order_status: 'ORDER STATUS',
  distance: 'Distance',
  total_time: 'Total Time',
  total_items: 'Total Items',
  delivery_fees: 'DELIVERY FEES',
  total: 'TOTAL',
  quantity: 'QUANTITY',
  price: 'PRICE',
  cart: 'CART',
  order_fees: 'ORDER FEES',
  earning: 'Earning',
  promo_setting: 'Promo Setting',
  promo_data: 'Promo Data',
};
export var lable_title = {
  cash: 'Cash',
  card: 'Card',
  absolute: 'Absolute',
  percentage: 'Percentage',
  order: 'Order',
  service: 'Service',
  active: 'Active',
  inactive: 'Inactive',
  expired: 'Expired',
  not_expired: 'Not Expired',
  store: 'Franchise',
  admin: 'Admin',
  sub_admin: 'Sub Admin',
  provider: 'Provider',
  user: 'User',
  provider_vehicle_type: 'Provider Vehicle',
  mandatory: 'Mandatory',
  optional: 'Optional',
  completed: 'COMPLETED',
  not_completed: 'NOT COMPLETED',
  delivery_fees_paid_by_store: 'DELIVERY FEES PAID BY FRANCHISE',
  asap: 'ASAP',

  created_at: 'Created At',
  store_accepted_at: 'Franchise Accepted At',
  preparing_order_at: 'Preparing Order At',
  order_ready_at: 'Order Ready At',
  store_order_send_at: 'Franchise Order Send At',
  provider_accepted_at: 'Provider Accepted At',

  start_for_pickup_at: 'Start for Pickup At',
  arrived_on_store_at: 'Arrived On Franchise At',
  picked_order_at: 'Picked Order At',
  start_for_delivery_at: 'Start For Delivery At',
  delivered_at: 'Delivered At',
  completed_at: 'Completed At',
};
