export var ERROR_CODE = {
  999: 'Token Expired',
  1000: 'Data Not Found',
  2000: 'Token Expired',
  2001: 'Set Password failed',

  601: 'Registration Failed',
  602: 'Email Already Registered',
  603: 'Mobile Number Already Registered',
  605: 'Already Registered With Social',
  606: 'Not Registered With Social',
  611: 'Login Failed',
  612: 'Email Not Registered',
  613: 'Invalid Passowrd',
  621: 'Update Failed',
  623: 'Logout Failed',
  631: 'Invalid Referral Code',
  632: 'Referral Already Used',
  633: 'Referral Process Failed',

  634: 'Store Data Not Found',
  635: 'Store Business Off',
  636: 'Order History Not Found',
  637: 'Order Detail Not Found',
  638: 'Otp Verification Failed',
  639: 'Email And Phone Number Already Registered',
  641: 'Daily Earning Not Found',
  642: 'Weekly Earning Not Found',

  871: 'Add Product Failed',
  872: 'Product Not Found',
  873: 'Update Product Failed',

  881: 'Specification Add Failed',
  882: 'Specification Not Found',

  891: 'Item Data Add Failed',
  892: 'Item Not Found',
  893: 'Item Image Upload failed',
  894: 'Item Image Update Failed',
  895: 'Item Update Failed',
  896: 'Item Status Changed failed',

  1001: 'Document Add Failed',
  1002: 'Document Not Found',
  1003: 'Document List Not Found',
  1004: 'Document Upload Failed',
  1005: 'Update Failed',

  1041: 'Specification Group Add Failed',
  1042: 'Specification Group List Not Found',
};
