export var menu_title = {
  create_order: 'Create Order',
  upload_document: 'Upload Document',
  order: 'Orders',
  deliveries: 'Deliveries',
  history: 'History',
  product: 'Category',
  item: 'Item',
  setting: 'Setting',
  earning: 'Earning',
  sub_earning: 'Earning',
  sub_daily_earning: 'Daily Earning',
  sub_weekly_earning: 'Weekly Earning',
  profile: 'Profile',
  logout: 'Logout',
  promocode: 'Promo code',
  menu: 'Menu',
  categories: 'Categories',
  products: 'Products',
  providers: 'Deliverymans',
  delivery_prices: 'Delivery Prices',
};

export var sub_menu_title = {
  user: 'User',
  block_user: 'Block User',
  online_providers: 'Online',
  approved_providers: 'Approved',
  declined_providers: 'Unapproved',
  stores: 'Stores',
  declined_stores: 'Unapproved',
  business_off_stores: 'Business Off',
};

export var setting_tab_title = {
  admin: 'Admin',
  logo: 'Logo',
  image_setting: 'Image Settings',
  google_key_settings: 'Google Key Settings',
  app_update_settings: 'App Update Settings',
  ios_push_notification: 'iOS Push Notification',
};

export var tooltip_title = {
  minimum_phone_number_length: 'Enter Minimum Phone No. Length',
  maximum_phone_number_length: 'Enter Maximum Phone No. Length',
  referral_bonus_to_user:
    'Please enter the amount of Referral bonus credit, User should get if his Referral code is used. Credit Currency will be default country currency.',
  referral_bonus_to_user_friend:
    "Please enter the amount of Referral bonus credit, User's friend should get. Credit Currency will be default country currency.",
  no_of_user_use_referral:
    "This number indicates maximum usage of user's referral code. If entered 2 then user's code will be used only 2 times by different friends.",
  referral_bonus_to_store:
    'Please enter the amount of Referral bonus credit, Store should get if his Referral code is used. Credit Currency will be default country currency.',
  referral_bonus_to_store_friend:
    "Please enter the amount of Referral bonus credit, Store's friend should get. Credit Currency will be default country currency.",
  no_of_store_use_referral:
    "This number indicates maximum usage of Store's referral code. If entered 2 then Store's code will be used only 2 times by different friends.",
  referral_bonus_to_provider:
    'Please enter the amount of Referral bonus credit, Deliveryman should get if his Referral code is used. Credit Currency will be default country currency.',
  referral_bonus_to_provider_friend:
    "Please enter the amount of Referral bonus credit, Deliveryman's friend should get. Credit Currency will be default country currency.",
  no_of_provider_use_referral:
    "This number indicates maximum usage of Deliveryman's referral code. If entered 2 then Deliveryman's code will be used only 2 times by different friends.",
  base_price_distance:
    'Select the value for free distance covered in base price. Eg. if selected 2 then distance price will not be charged till 2 km or miles.',
  surge_multiplier: 'Surge Multiplier',
  base_price:
    'Base price for this service type. Eg. $5 is the base price for SUV.',
  price_per_unit_distance: 'Price per km or mile for this service type.',
  price_per_unit_time: 'Price per unit time for this service type.',
  service_tax: 'Percentage of tax on the total invoice.',
  min_fare: 'Minimum fare.',
  cancellation_fee: 'This is the fees charged on cancellation of the Order.',
  set_price_for_zone_to_zone: 'Set fix delivery price for zone to zone.',
};
export var filter = {};

export var date_time_title = {};

export var title = {
  //////////  date_time_title
  database_backup: 'Database Backup',
  add_tags: 'Add Tags',
  change_status: 'Change Status',
  create_backup: 'Create Database Backup',
  first_name: 'First Name',
  last_name: 'Last Name',
  assigned_date: 'Assigned Date',
  expiry_date: 'Expiry Date',
  start_date: 'Start Date',
  end_date: 'End Date',
  is_deleted_from_db: 'Deleted from database',
  complete_date: 'Completed Date',
  create_date: 'Created Date',
  start_time: 'Start Time',
  end_time: 'End Time',
  date: 'Date',
  day: 'Day',
  week: 'Week',
  month: 'Month',
  time: 'Time',
  year: 'Year',
  sunday: 'Sun',
  monday: 'Mon',
  tuesday: 'Tue',
  wednesday: 'Wed',
  thursday: 'Thu',
  friday: 'Fri',
  saturday: 'Sat',
  select_vehicle: 'Select Vehicle',

  ////// for filter
  SET_BY_ADMIN: 'Set By Admin',
  ADDED_BY_CARD: 'Added By Card',
  ADDED_BY_REFERRAL: 'Added By Referral',
  ORDER_CHARGED: 'Order Charged',
  ORDER_REFUND: 'Order Refund',
  SET_ORDER_PROFIT: 'Order Profit',
  ORDER_CANCELLATION_CHARGE: 'Order Cancellation Charge',
  SET_BY_WALLET_REQUEST: 'Set by Wallet Request',
  sort: 'Sort',
  search: 'Search',
  date_filter: 'Date Filter',
  ascending: 'Ascending',
  descending: 'Descending',
  comment: 'Comment',
  profit_mode: 'Profit Mode',
  dashboard: 'Dashboard',
  delivery_info: 'Delivery Info',
  map_view: 'Map View',
  templates: 'Templates',
  reports: 'Reports',
  months: 'month',
  weeks: 'week',
  days: 'day',
  order: 'Order',
  checkout_amount: 'Checkout Amount',
  profit_value: 'Profit Value',
  orders: 'Orders',
  delivery: 'Delivery',
  deliveries: 'Deliveries',
  history: 'History',
  payment: 'Payment',
  payments: 'Payments',
  approved: 'Approved',
  unapproved: 'Unapproved',
  online: 'Online',
  offline: 'Offline',
  close: 'Close',
  images: 'Images',
  business_off: 'Business Off',
  provider_track: 'Deliveryman Track',
  deliveries_prices: 'Deliveries Prices',
  request_cancellation_reason: 'Cancelled Delivery',
  earning: 'Earning',
  order_earning: 'Order Earning',
  provider_weekly_earning: 'Deliveryman Weekly Earning',
  store_weekly_earning: 'Store Weekly Earning',
  promo_code: 'Promo Code',
  referral_detail: 'Referral Detail',
  wallet_history: 'Wallet History',
  wallet_request: 'Wallet Request',
  transaction_history: 'Transaction History',
  ads: 'Ads',
  send_mass_notification: 'Send Mass Notification',
  notification_settings: 'Notification Settings',
  send_group_notification: 'Send Group Notification',
  admin: 'Admin',
  sub_admin: 'Sub Admin',
  user: 'User',
  users: 'Users',
  provider: 'Deliveryman',
  providers: 'Deliverymans',
  store: 'Store',
  stores: 'Stores',
  settings: 'Settings',
  admin_settings: 'Admin Settings',
  app_settings: 'App Settings',
  location: 'Location',
  vehicle: 'Vehicle',
  store_location: 'Store Location',
  provider_location: 'Provider Location',
  country: 'Country',
  city: 'City',
  full_name: 'Full Name',
  review: 'Review',
  document: 'Document',
  documents: 'Documents',
  mail: 'Mail',
  sms: 'SMS',
  detail: 'Detail',
  details: 'Details',
  no_of_record: 'No. of record',
  referred_to: 'Referred to',
  payment_mode: 'Payment Mode',
  item_price: 'Item Price',
  tax_price: 'Tax Price',
  earn: 'Earn',
  card: 'Card',
  cash: 'Cash',
  wallet: 'Wallet',
  other: 'Other',
  promo: 'Promo',
  promo_payment: 'Promo Payment',
  card_payment: 'Card Payment',
  cash_payment: 'Cash Payment',
  wallet_payment: 'Wallet Payment',
  other_payment: 'Other Payment',
  order_payment: 'Order Payment',
  delivery_payment: 'Delivery Payment',
  user_payment: 'User Payment',
  store_profit: 'Store Profit',
  admin_profit: 'Admin Profit',
  admin_order_profit: 'Admin Order Profit',
  admin_delivery_profit: 'Admin Delivery Profit',
  deliveryman_profit: 'Deliveryman Profit',
  deliveryman_income: 'Deliveryman Income',
  store_income: 'Store Income',
  profit: 'Profit',
  profilt_mode: 'Profit Mode',
  convert_rate: 'Convert Rate',
  all: 'All',
  business: 'Business',
  visible: 'Visible',
  invisible: 'Invisible',
  active: 'Active',
  inactive: 'Inactive',
  yes: 'YES',
  no: 'NO',
  like: 'Like',
  dislike: 'Dislike',
  url: 'Url',
  name: 'Name',
  image: 'Image',
  icon: 'Icon',
  map_pin: 'Map Pin',
  color: 'Color',
  code: 'Code',
  currency: 'Currency',
  timezone: 'Timezone',
  km: 'Km',
  mile: 'Mi',
  miles: 'Mile',
  id: 'ID',
  unique_id: 'Unique Id',
  email: 'Email',
  phone: 'Phone',
  rate: 'Rate',
  action: 'Action',
  qty: 'Quantity',
  spec: 'Spec.',

  // for provider
  total: 'Total',
  accepted: 'Accepted',
  cancelled: 'Cancelled',
  completed: 'Completed',
  rejected: 'Rejected',
  password: 'Password',
  new_password: 'New Password',
  confirm_password: 'Confirm Password',
  old_password: 'Old Password',
  forgot_password: 'Forgot Password',
  admin_title1: 'Welcome to',
  app_name: 'yeepeey.',
  // admin_title2: 'Admin Panel',
  admin_title2: '',
  signin_to_your_account: 'Sign in to your account',
  referred_by: 'Referred By',
  total_referrals: 'Total Referrals',
  referral: 'Referral',
  referred: 'Referred',
  referral_user: 'Referral User',
  document_uploaded: 'Document Uploaded',
  phone_number_verified: 'Phone Verified',
  email_verified: 'Email Verified',
  app_version: 'App Version',
  device_type: 'Device Type',
  active_for_job: 'Active For Job',
  website_url: 'Website Url',
  slogan: 'Slogan',
  famous_for: 'Famous For',
  device_type_android: 'Android',
  device_type_ios: 'Ios',
  both: 'Both',
  message: 'Message',
  price_rating: 'Price Rating',
  is_use_wallet: 'Use Wallet',
  specification: 'Specification',
  specifications: 'Specifications',
  product: 'Product',
  category: 'Category',
  products: 'Products',
  item: 'Item',
  items: 'Items',

  //history
  status: 'Status',
  order_type: 'Order Type',
  asap: 'ASAP',
  schedule: 'Schedule',
  payment_by: 'Payment By',
  default_price: 'Default Pricing',

  // earning
  fees: 'Fees',
  address: 'Address',
  price: 'Price',
  distance: 'Distance',

  /////// title with detail
  is_auto_transfer_for_store: 'Auto transfer for store',
  auto_transfer_day_for_store: 'Auto transfer day for store',
  is_auto_transfer_for_deliveryman: 'Auto transfer for deliveryman',
  auto_transfer_day_for_deliveryman: 'Auto transfer day for deliveryman',
  to_store: 'To Store',
  to_deliveryman: 'To Deliveryman',
  to_user: 'To User',
  not_available: 'Not Available',
  cancellation_charge: 'Cancellation Charge',
  is_store_can_add_provider: 'Store Can Add Provider',
  is_main_store: 'Main Store',
  is_store_can_set_delivery_prices: 'Store Can Set Delivery Prices',
  is_store_can_complete_order: 'Store Can Complete Order',
  online_with_order: 'Online With Order',
  offline_with_order: 'Offline With Order',
  delivery_man_online_with_order: 'Deliveryman Online With Order',
  delivery_man_offline_with_order: 'Deliveryman Offline With Order',
  provider_vehicle_plate_no: 'Plate No.',
  provider_vehicle_model: 'Model',
  provider_vehicle_service_type: 'Service Type',
  registered_date: 'Registered Date',
  provider_vehicle: 'Provider Vehicle',
  from_distance: 'From Distance',
  to_distance: 'To Distance',
  driver_fee: 'Driver Fee',

  ///////////////for country //////////////////////////
  country_timezone: 'Country Timezone',
  currency_code: 'Currency Code',
  currency_sign: 'Currency Sign',
  country_phone_code: 'Country Phone Code',
  phone_number_length: 'Phone Number Length',
  minimum_phone_number_length: 'Minimum Phone No. Length',
  maximum_phone_number_length: 'Maximum Phone No. Length',
  referral_bonus_to_user: 'Referral Bonus to User',
  bonus_to_user_referral: "Referral Bonus to User's Friend",
  referral_bonus_to_store: 'Referral Bonus to Store',
  bonus_to_store_referral: "Referral Bonus to Store's Friend",
  referral_bonus_to_provider: 'Referral Bonus to Deliveryman',
  bonus_to_provider_referral: "Referral Bonus to Deliveryman's Friend",
  is_distance_unit_mile: 'Distance Unit Mile',
  referral_for_user: 'Referral For User',
  referral_for_store: 'Referral For Store',
  referral_for_provider: 'Referral For Deliveryman',

  ///////////////for city //////////////////////////
  promo_apply: 'Promo Apply',
  city_radius: 'City Radius',
  city_lat: 'Latitude',
  city_lng: 'Longitude',
  select: 'Select',
  languages: 'Languages',
  description: 'Description',
  is_use_distance_calculation: 'Use Distance Calculation',
  add_delivery_price_setting: 'Add Delivery Price',
  is_check_provider_wallet_amount_for_received_cash_request:
    'Check Wallet Amount For Cash',
  provider_min_wallet_amount_for_received_cash_request:
    'Deliveryman Min. Wallet Amount For Cash',
  provider_earning_add_in_wallet_using_cash:
    'Deliveryman Amount Add In Wallet By Cash Payment',
  provider_earning_add_in_wallet_using_other:
    'Deliveryman Amount Add In Wallet By Other Payment',
  store_earning_add_in_wallet_using_cash:
    'Store Amount Add In Wallet By Cash Payment',
  store_earning_add_in_wallet_using_other:
    'Store Amount Add In Wallet By Other Payment',
  // NEW
  zone: 'Zone',
  use_radius: 'Use Radius',
  ////////////////// for delivery /////////////////////
  famous_products_tags: 'Products Tags',
  sequence_number: 'Sequence Number',
  ////////// for service //////////////////////////
  base_price_distance: 'Base Price Distance',
  base_price: 'Base Price',
  price_per_unit_distance: 'Price Per Unit Distance',
  price_per_unit_time: 'Price Per Unit Time',
  service_tax: 'Service Tax',
  surge_price: 'Surge Price',
  min_fare: 'Min Fare',
  cancellation_fee: 'Cancellation Fees',
  surge_hours: 'Surge Hour',
  is_surge_hours: 'Surge Hour',
  surge_multiplier: 'Surge Multiplier',
  surge_start_hour: 'Surge Start Hour',
  surge_end_hour: 'Surge End Hour',
  last_updated: 'Last Updated',
  created: 'Created',
  total_item_sold: 'Total Item Sold',
  delivery_time: 'Delivery Time',
  store_item_tax: 'Item Tax',
  set_time: 'Set Time Schedule',
  store_time: 'Store Time',
  free_delivery_for_above_order_price: 'Free Delivery Above Price',
  is_store_pay_delivery_fees: 'Store Pay Delivery Fee',

  // For Promo code
  is_promo_user_required_uses: 'Promo User Uses Required',
  is_promo_required_uses: 'Promo Uses Required',
  is_promo_have_minimum_amount_limit: 'Min. Amount Limit',
  is_promo_have_max_discount_limit: 'Max. Discount Limit',
  promo_code_apply_on_minimum_amount: 'Min. Amount',
  promo_code_max_discount_amount: 'Max.Discount Amount',
  admin_loyalty: 'Loyalty',
  promo_created_loyalty: 'Promo Created Loyalty',
  promo_for: 'Promo For',
  admin_loyalty_type: 'Loyalty Type',
  created_by: 'Created By',
  value: 'Value',
  type: 'Type',
  promo_code_uses: 'Number Of Uses',
  is_expired: 'Expiry?',
  promo_for_delivery_service: 'Promo For Delivery Service',
  uses: 'Uses',
  user_used: 'User Used',
  promo_apply_on: 'Promo Apply On',

  //FOR NEW PROMO STRING
  is_promo_apply_on_completed_order: 'Apply after completion',
  promo_apply_after_completed_order: 'Minimum Complete Order',
  promo_recursion_type: 'Recursion Type',
  min_item_limit: 'Minimum Item Limit',

  //promo_store:"Store",
  promo_for_delivery: 'Deliveries',
  promo_delivery_service: 'Delivery Service',
  promo_product: 'Product',
  promo_item: 'Item',
  contact_email: 'Contact Email',
  contact_phone: 'Contact Phone',
  admin_panel_timezone: 'Admin Panel TimeZone',
  admin_logo: 'Logo',
  admin_title_icon: 'Title Icon',
  admin_mail_title_icon: 'Mail BackGround Image',
  admin_store_logo: 'Store Logo',
  admin_mail_logo: 'Mail Logo',
  admin_user_logo: 'User Logo',

  //for app settings
  admin_provider_timeout: 'Deliveryman TimeOut',
  admin_store_timeout: 'Store TimeOut',
  admin_app_name: 'App Name',
  admin_default_search_radius: 'Default Search Radius',
  admin_scheduled_request_pre_start_minute:
    'Scheduled Request Pre Start Minutes',
  admin_number_of_try_for_scheduled_request:
    'Number Of Loop For Scheduled Request',

  // for google key settings
  android_user_app_gcm_key: 'Android User App Gcm Key',
  android_provider_app_gcm_key: 'Android Deliveryman App Gcm Key',
  android_store_app_gcm_key: 'Android Store App Gcm Key',
  android_user_app_google_key: 'Android User App Google Key',
  android_provider_app_google_key: 'Android Deliveryman App Google Key',
  android_store_app_google_key: 'Android Store App Google Key',
  ios_user_app_google_key: 'IOS User App Google Key',
  ios_provider_app_google_key: 'IOS Deliveryman App Google Key',
  ios_store_app_google_key: 'IOS Store App Google Key',
  admin_panel_google_key: 'Admin Panel Google Key',
  store_panel_google_key: 'Store Panel Google Key',
  branch_io_key: 'Branch Io Key',

  // other switch
  login_by_social: 'Social Login',
  use_referral: 'Use Referral',
  verify_email: 'Verify Email',
  verify_phone: 'Verify Phone',
  upload_documents: 'Upload Documents',
  login_by_email: 'Login By Email',
  login_by_phone: 'Login By Phone',
  profile_picture_required: 'Profile Picture',
  show_optional_field: 'Show Optional Field',
  earning_add_in_wallet_using_cash: 'Amount Add In Wallet By Cash Payment',
  earning_add_in_wallet_using_other: 'Amount Add In Wallet By Other Payment',
  email_id_required: 'Email Required',
  phone_required: 'Phone Required',
  sms_notification: 'SMS Notification',
  mail_notification: 'Email Notification',
  push_notification: 'Push Notification',
  pickup_delivery_confirmation_code: 'Pickup Delivery Confirmation Code',
  complete_delivery_confirmation_code: 'Complete Delivery Confirmation Code',

  // for app Update setting
  open_update_dialog: 'Open Update Dialog',
  force_update: 'Force Update',
  certificate_mode: 'Certificate Mode',
  push_certificate: 'Push Certificate',
  push_p8_file: 'Push P8 File',
  push_key_file: 'Push Key File',
  bundle_id: 'Bundle Id',
  team_id: 'Team Id',
  key_id: 'Key Id',
  passprase: 'Passprase',
  sandbox_mode: 'Sandbox',
  production_mode: 'Production',

  // for document
  is_mandatory: 'Mandatory',
  is_unique_code: 'Unique Code',
  option: 'Option',
  unique_code: 'Code',
  item_note_here: 'Item Note',

  //for sms
  sms_unique_title: 'SMS Unique Title',
  select_sms_unique_title: 'Select SMS Unique Title',
  is_send: 'Send',
  //for email
  email_unique_title: 'Email Unique Title',
  email_title: 'Email Title',
  email_admin_info: 'Email Admin Info',
  email_content: 'Email Content',
  //for add wallet
  amount: 'Amount',
  transfer_status: 'Transfer Status',
  transfered_by: 'Transfered By',
  transfered_by_admin: 'Admin',
  transfer: 'Transfer',
  not_transfer: 'Not Transfer',
  // for admin sms
  content: 'Write SMS Content',
  notification_content: 'Write Notification Content',
  // For Provider Weekly Earning
  admin_earn: 'Admin Earn',
  admin_earn_in_wallet: 'Admin Earn wallet',
  total_orders: 'Total Orders',
  provider_earn: 'Deliveryman Earn',
  pay_to_provider: 'Pay/Collect',
  have_case: 'Have Cash',
  pay_collect: 'Pay/Collect',
  paid: 'Paid',
  remaining_to_pay: 'Remaining to Pay',
  view_week_statement: 'View Week Statement',
  pay: 'Pay',
  cancelled_by: 'Cancelled By',
  cancellation_reason: 'Cancellation Reason',
  store_earn: 'Store Earn',
  pay_to_store: 'Pay/Collect',
  store_have_payment: 'Received Payment',
  provider_earning: 'Deliveryman Earning',
  deliveries_payment: 'Deliveries Payment',
  delivery_at: 'Delivery Date',
  store_bear_delivery_fee: 'Store bear delivery fee?',
  deliveryman_paid_order_cash_to_store: 'Deliveryman paid order cash to store?',
  sattlement_with_store: 'Sattlement with store',
  sattlement_with_deliveryman: 'Sattlement with deliveryman',
  payment_status: 'Payment Status',
  wallet_amount: 'Wallet Amount',
  from_where: 'From Where?',
  add_cut: 'Add/Cut',
  order_start_at: 'Start Date',

  // earning
  invoice_number: 'INVOICE NO.',
  invoice_date: 'DATE',
  distance_price: 'Distance Price',
  delivery_fee: 'Delivery Fees',
  time_price: 'Time Price',
  service_price: 'SERVICE PRICE',
  pickup: 'Pick up',
  cart: 'CART',
  order_fee: 'ORDER FEES',
  cart_price: 'Cart Price',
  store_tax_price: 'Tax Price',
  order_price: 'Order Price',
  total_online_time: 'Online Time',
  job_time: 'Job Time',
  not_answered: 'Not Answered',
  sms_api_key: 'API Key',
  sender_id: 'Sender ID',
  sms_configuration_auth_id: 'Auth ID',
  sms_auth_token: 'Auth Token',
  sms_number: 'Number',
  sms_gateway_name: 'SMS Gateway',
  total_transferred_amount: 'Transferred',
  paid_service_fee: 'Paid Service Fee',
  no_of_item: 'No Of Item',
  total_cart_price: 'Total Cart Price',
  total_store_income: 'Total Store Income',
  received_order_amount: 'Received Order Amount',
  paid_order_amount: 'Paid Order Amount',
  deduct_from_wallet: 'Deduct from wallet',
  added_in_wallet: 'Added in wallet',
  total_earnings: 'Total Earnings',
  paid_in_wallet: 'PAID IN WALLET',
  beneficiary_address: 'Beneficiary Address',
  bank_swift_code: 'Bank Swift Code',
  branch: 'Branch',
  account_number: 'Account Number',
  ads_type: 'Ads Type',
  website: 'Website',
  delivery_list: 'Delivery List',
  store_list: 'Store List',
  in_store: 'In Store',
  redirect_to_store: 'Redirect To Store?',
  ratio_should_be: 'Ratio Should Be',
  min_width: 'Min Width',
  max_width: 'Max Width',
  min_height: 'Min Height',
  max_height: 'Max Height',
  min: 'Minimum',
  max: 'Maximum',
  open_full_time: 'Open Full Time',
  open: 'Open',
  image_size_error: 'Image Size Not Proper',
  image_ratio_error: 'Image Ratio Not Proper',
  image_extension_error: 'Image Extension Not Proper',
  reviewed_by: 'Reviewed by',
  icon_image_note: 'Upload image size within width x height ( ',
  image_note1: 'Upload image size within width x height (min ',
  image_note2: ' and max ',
  image_note3: 'Image ratio should be ',
  image_note4: ' and upload only ',
  image_note5: ' file',
  note_for_image: 'Image Note',
  note_for_map_pin: 'Map Pin Note',
  note_for_icon: 'Icon Note',
  provider_paid_order: 'Deliveryman Paid Order',
  earning_store_have_payment: 'Store Have Payment',
  cash_card: 'Cash/Card',
  provider_have_cash: 'Deliveryman Have Cash',
  provider_fees: 'Deliveryman Fees',
  pay_provider: 'Pay Deliveryman',
  store_fees: 'Store Fees',
  store_paid_delivery_fees: 'Store Paid Delivery Fees',
  pay_store: 'Pay Store',
  cancellation_fees: 'Cancellation Fees',
  refund_amount: 'Refund Amount',
  provider_income_set_in_wallet: 'Deliveryman Set Wallet',
  order_id: 'Order ID',
  user_id: 'User ID',
  request_id: 'Request ID',
  provider_id: 'Deliveryman ID',
  store_id: 'Store ID',
  total_wallet_income_set_in_cash_order: 'Wallet Deduct',
  total_wallet_income_set_in_other_order: 'Added In Wallet',
  store_income_set_in_wallet: 'Store Set Wallet',
  total_item: 'Total Items',
  delivery_price: 'Delivery Price',
  promo_bonus: 'Promo Bonus',
  store_have_service_payment: 'Store Have Service Payment',
  store_have_order_payment: 'Store Have Order Payment',
  provider_have_cash_payment: 'Provider have cash payment',
  admin_profit_on_store: 'Admin Order Profit',
  admin_profit_on_delivery: 'Admin Delivery Profit',
  total_referred: 'Total Referred',
  referral_code: 'Referral Code',
  offer: 'Offer',
  remining_to_pay: 'REMAINING TO PAY',
  read_more: 'Read',
  user_review_to_provider: 'User To Deliveryman',
  user_review_to_store: 'User To Store',
  provider_review_to_user: 'Deliveryman To User',
  provider_review_to_store: 'Deliveryman To Store',
  store_review_to_provider: 'Store To Deliveryman',
  store_review_to_user: 'Store To User',
  bank_account_holder_name: 'Bank Account Holder',
  ads_for: 'Ads For',
  image_for_banner: 'Banner Image',
  image_for_fullscreen: 'Fullscreen Image',
  block: 'BLOCK',
  general: 'General',
  for_delivery: 'For Delivery',
  banner: 'Banner',
  fullscreen: 'Fullscreen',
  delivery_type: 'Delivery Type',

  delivery_image_size_error: 'Image Size Not Proper',
  delivery_image_ratio_error: 'Image Ratio Not Proper',
  delivery_image_extension_error: 'Image Extension Not Proper',
  vehicle_image_size_error: 'Image Size Not Proper',
  vehicle_image_ratio_error: 'Image Ratio Not Proper',
  vehicle_image_extension_error: 'Image Extension Not Proper',
  ads_image_size_error: 'Image Size Not Proper',
  ads_image_ratio_error: 'Image Ratio Not Proper',
  ads_image_extension_error: 'Image Extension Not Proper',
  remaining: 'Remaining',
  delivery_address: 'DELIVERY ADDRESS',

  /////////////// labels
  absolute: 'Absolute',
  percentage: 'Percentage',
  not_completed: 'NOT COMPLETED',
  delivery_fees_paid_by_store: 'DELIVERY FEES PAID BY STORE',
  not_expired: 'Not Expired',
  created_at: 'Created At',
  store_accepted_at: 'Store Accepted At',
  preparing_order_at: 'Preparing Order At',
  order_ready_at: 'Order Ready At',
  store_order_send_at: 'Store Order Send At',
  provider_accepted_at: 'Deliveryman Accepted At',
  start_for_pickup_at: 'Start for Pickup At',
  arrived_on_store_at: 'Arrived On Store At',
  picked_order_at: 'Picked Order At',
  start_for_delivery_at: 'Start For Delivery At',
  delivered_at: 'Delivered At',
  completed_at: 'Completed At',
  courier: 'Courier',
};

export var heading_title = {
  daily_earning: 'Daily Earning',
  store_transactions: 'Store transactions',
  add_vehicle: 'Add Vehicle',
  delivery_price_setting: 'Delivery Price Setting',
  order_by: 'ORDER BY',
  order_to: 'ORDER TO',
  deliver_by: 'DELIVERED BY',
  admin_menu: 'Menu list',
  order_user_detail: 'Order User Detail',
  create_mass_notification: 'Create Mass Notification',
  order_fees: 'ORDER FEES',
  earning: 'Earning',
  delivery_fees: 'DELIVERY FEES',
  dashboard_register_detail: 'Register Details',
  dashboard_order_detail: 'Order Details',
  dashboard_payment_detail: 'Payment Details',
  review_detail: 'Review Detail',
  dashboard_admin_payment: 'Admin Payments',
  dashboard_store_payment: 'Store Payments',
  dashboard_provider_payment: 'Deliveryman Payments',
  dashboard_title: 'Earning',
  dashboard_order_chart: 'Order bar Chart',
  dashboard_last_six_month_payment_detail: 'Last 6 months Payment Details',
  rejection_reason: 'REJECTION REASON',
  cancellation_reason: 'CANCELLATION REASON',
  referral_setting: 'Referral Setting',
  country_data: 'Country Data',
  setting: 'Setting',
  city_setting: 'City Setting',
  country_setting: 'Country Setting',
  delivery_setting: 'City Setting',
  vehicle_setting: 'City Setting',
  service_setting: 'Service Setting',
  city_data: 'City Data',
  service_data: 'Service Data',
  surge_hour_data: 'Surge Hour Data',
  vehicle_data: 'Vehicle data',
  delivery_data: 'Delivery Data',
  payment_data: 'Payment Data',
  document_data: 'Document Data',
  total_order: 'Total Order',
  accepted_order: 'Accepted Order',
  rejected_order: 'Rejected Order',
  completed_order: 'Completed Order',
  total_item_sold: 'Total Item Sold',
  accepted_ratio: 'Accepted Ratio',
  rejected_ratio: 'Rejected Ratio',
  completed_ratio: 'Completed Ratio',
  assigned_date: 'Assigned Date',
  order_for: 'ORDER FOR',
  not_answered: 'Not Answered',
  store_time: 'Store Time',
  // app update
  android_user_app: 'Android User App',
  android_provider_app: 'Android Deliveryman App',
  android_store_app: 'Android Store App',
  ios_user_app: 'IOS User App',
  ios_provider_app: 'IOS Deliveryman App',
  ios_store_app: 'IOS Store App',
  user_app: 'User App',
  provider_app: 'Deliveryman App',
  store_app: 'Store App',
  other_setting: 'Other Settings',
  promo_data: 'Promo Data',
  promo_setting: 'Promo Settings',
  admin_data: 'Admin Data',
  sms_data: 'SMS DATA',
  email_data: 'EMAIL DATA',
  add_wallet_amount: 'Add Wallet Amount',
  admin_sms: 'Send SMS',
  admin_send_notification: 'Send Notification',
  email_configuration: 'Email Configuration',
  sms_configuration: 'SMS Configuration',
  history: 'History',
  deliveries: 'Deliveries',
  order_list: 'Order List',
  order_detail: 'ORDER DETAILS',
  user_detail: 'USER DETAIL',
  delivery_user_detail: 'DELIVERY USER DETAIL',
  provider_detail: 'DELIVERYMAN DETAIL',
  store_detail: 'STORE DETAIL',
  order_status: 'ORDER STATUS',
  request_status: 'REQUEST STATUS',
  vehicle: 'Vehicle',
  wallet: 'Wallet',
  referral: 'Referral',
  private_message: 'Private Message',
  service_detail: 'Service Detail',
  promo_info: 'Promo Info',
  user_info: 'User Info',
  order_earning: 'ORDER EARNING',
  daily_order_earning: 'DAILY ORDER EARNING',
  provider_transaction: 'DELIVERYMAN TRANSACTION',
  store_transaction: 'STORE TRANSACTION',
  payment_gateway_data: 'PAYMENT GATEWAY DATA',
  bank_detail: 'Bank',
  ads_data: 'Ads Data',
  advertise_data: 'Advertise Data',
  image_size_for_delivery: 'Image Size Use For Delivery/Product/Item',
  image_size_for_map: 'Image Size For Map Pin For Apps',
  image_icon_size: 'Image Icon Size',
  order_from: 'Order From',
  delivery_to: 'Delivery To',
  payment: 'Payment',
  delivery_man: 'Deliveryman',
  store: 'Store',
  card: 'Card',
  cash: 'Cash',
};

export var button = {
  add: 'Add',
  edit: 'Edit',
  delete: 'Delete',
  save: 'Save',
  submit: 'Submit',
  update: 'Update',
  login: 'Login',
  register: 'Register',
  close: 'Close',
  decline: 'Decline',
  approved: 'Approve',
  send: 'Send',
  apply: 'Apply',
  export_excel: 'Export',
  accept: 'Accept',
  cancel: 'Cancel',
  transfer: 'Transfer',
  complete: 'Complete',
  done: 'Done',

  add_city: 'Add City',
  add_country: 'Add Country',
  add_delivery: 'Add Delivery',
  add_vehicle: 'Add Vehicle',
  add_service: 'Add Service',
  add_payment: 'Add Payment',
  add_wallet: 'Add Wallet',
  add_document: 'Add Document',
  add_promo: 'Add Promo',
  add_admin: 'Add Admin',
  add_ads: 'Add Ads',

  inActive: 'InActive',
  active: 'Active',

  view_products: 'View Category',
  view_setting: 'View setting',
  view_map: 'View Map',
  view_invoice: 'View Invoice',
  view_uses: 'View Uses',
  view_cart: 'View Cart Detail',

  usage: 'usage',
  select_file: 'Select File',
  remove_file: 'Remove File',
  upload_file: 'Upload File',
  detail: 'Detail',
  send_sms: 'Send SMS',
  send_notification: 'Send Notification',
  pre: 'Pre',
  next: 'Next',
  goto: 'Goto',
  reviews: 'Review',
  referral: 'Referral',
  bank_detail: 'Bank Detail',
  view_document: 'Documents',
  reassign: 'Reassign',

  restore: 'Restore',
  download: 'Download',
};

export var wallet_request_status = {
  created: 'Created',
  sent: 'Sent',
  accepted: 'Accepted',
  transfered: 'Transfered',
  completed: 'Completed',
  cancelled: 'Cancelled',
};

export var status = {
  created: 'Created',
  waiting_for_accept1: 'Order Created',
  accepted1: 'Accepted',
  start_preparing_order1: 'In progress',
  order_ready1: 'Ready',
  waiting_for_delivery_man1: 'Assigned',
  delivery_man_accepted1: 'Accepted',
  delivery_man_coming1: 'Coming',
  delivery_man_arrived1: 'Arrived',
  picked_order1: 'Picked up',
  started_for_delivery1: 'Delivering',
  arrived_at_destination1: 'Delivering',
  delivered_ordered1: 'Completed',
  assign_order_to_Delivery_man1: 'Assign To Deliveryman',
  no_delivery_man_found1: 'No Found',
  delivery_man_rejected1: 'Rejected',
  delivery_man_cancelled1: 'Rejected',
  user_cancelled1: 'Cancle By User',
  oredr_complete: 'Order Completed',
  order_delivered: 'Delivered',
  completed: 'Completed',
  rejected1: 'Rejected',
  cancelled1: 'Cancelled',
  not_completed: 'Not Completed',
  user_cancelled: 'User cancelled',
  cancelled_request1: 'Not Assigned',
  waiting_for_accept: 'New Order Created',
  accepted: 'Accepted',
  start_preparing_order: 'Started Preparing',
  order_ready: 'Order is ready',
  waiting_for_delivery_man: 'Assigned to Deliveryman',
  delivery_man_accepted: 'Deliveryman accepted',
  delivery_man_coming: 'Deliveryman is coming',
  delivery_man_arrived: 'Deliveryman arrived',
  picked_order: 'Deliveryman picked up order',
  started_for_delivery: 'Delivering',
  arrived_at_destination: 'Deliveryman arrived at destination',
  delivered_ordered: 'Order Delivered',
  assign_order_to_Delivery_man: 'Assign To Deliveryman',
  rejected: 'Store rejected',
  cancelled: 'Store cancelled order',
  no_delivery_man_found: 'Deliveryman not found',
  delivery_man_rejected: 'Deliveryman Rejected',
  delivery_man_cancelled: 'Deliveryman cancelled',
  cancelled_request: 'Request Cancelled',
};

export var message = {
  country_already_exist: 'Country Already Exist',
  promo_code_already_exist: 'Promo Code Already Exist',
};
