export var validation_message = {
  email_required: 'Email is required',
  valid_email: 'Please Enter Valid Email Address',
  phone_required: 'Phone Number is required',
  phone_minlength: 'Please Enter Atleast Character',
  phone_maxlength: 'Do Not Enter More Than Character',
  name_required: 'Name  is required',
  address_required: 'Address  is required',
  range_validation_error: 'Please select valid range',
  latitude_required: 'Latitude  is required',
  longitude_required: 'Longitude  is required',
  password_required: 'Password is required',
  password_minlength: 'Please Enter Atleast Character',
  item_tax_required: 'Item Tax is required',
  delivery_time_required: 'Delivery Time is required',
  delivery_time_max_required: 'Max Delivery Time is required',
  free_delivery_for_above_order_price_required: 'Price is required',
  free_delivery_within_radius_required: 'Radius is required',
  store_open_time_required: 'Store Open Time is required',
  store_close_time_required: 'Store Close Time is required',
  product_name_required: 'Product Name is required',
  product_detail_required: 'Product Detail is required',
  product_image_required: 'Product Image is required',

  select_product_required: 'Select Product',
  item_name_required: 'Item Name is required',
  item_detail_required: 'Item Detail is required',
  item_price_required: 'Item price is required',
  match_confirm_password: 'Not match',

  select_country_required: 'Select Country First',

  select_city_required: 'Select City First',
  select_delivery_type_required: 'Select Delivery Type First',

  select_business_type_required:'Select Business Type First',

  email_otp_wrong: 'Email Otp Wrong',
  sms_otp_erong: 'Sms Otp Wrong',
  otp_wrong: 'Opt Wrong',

  open_time_not_greater_close_time: 'Open Time Not Greater Than Close Time',
  invalid_open_time: 'Invalid Open Time',
  close_time_not_less_open_time: 'Close Time Not Less Than Open Time',
  invalid_close_time: 'Invalid Close Time',

  image_required: 'Image is required',
  unique_code_required: 'Unique Code is required',
  expired_date_required: 'Expiry date is required',
  email_or_phone_required: 'Email Or Phone required',
  valid_email_or_phone: 'Enter Valid Email or Phone',
  confirmation_code_wrong: 'Confirmation Code Wrong',
};
