export var menu_title = {
  create_order: 'Create Order',
  upload_document: 'Upload Document',
  order: 'Orders',
  deliveries: 'Deliveries',
  history: 'History',
  product: 'Category',
  item: 'Item',
  setting: 'Setting',
  earning: 'Earning',
  sub_earning: 'Earning',
  sub_daily_earning: 'Daily Earning',
  sub_weekly_earning: 'Weekly Earning',
  profile: 'Profile',
  logout: 'Logout',
  promocode: 'Promo code',
  menu: 'Menu',
  categories: 'Categories',
  products: 'Products',
  providers: 'Deliverymans',
  delivery_prices: 'Delivery Prices',
};

export var title = {
  select_vehicle: 'Select Vehicle',
  vat: 'VAT(%)',
  is_use_item_tax: 'Use Item Tax',
  enter_modifier_group_name: 'Enter Modifier Group Name',
  update_price_desc_and_vat: 'Update Item Price Description and VAT',
  product_price: 'Product Price',
  admin_email: 'Admin Email',
  admin_phone: 'Admin Phone',
  order_start_at: 'Order Start At',
  asap: 'ASAP',
  km: 'Km',
  is_store_can_add_provider: 'Store Can Add Provider',
  is_store_can_set_delivery_prices: 'Store Can Set Delivery Prices',
  is_store_can_complete_order: 'Store Cane Complete Order',
  schedule: 'Schedule',
  deliveryman: 'Delivery Man',
  created_by: 'Created By',
  ///////////////for store Register //////////////////////////
  language: 'Language',
  is_ask_estimated_time_for_ready_order:
    'Assign to Deliveryman when order is accepted',
  name: 'Name',
  email: 'Email',
  password: 'Password',
  confirm_password: 'Confirm Password',
  website_url: 'Website Url',
  slogan: 'Slogan',
  select_country: 'Select Country',
  select_city: 'Select City',
  address: 'Address',
  country_phone_code: 'Phone Code',
  phone: 'Phone Number',
  fax_number: 'Fax Number',
  select_delivery: 'Selct Delivery Type',
  latitude: 'Latitude',
  longitude: 'Longitude',
  famous_for: 'Famous For',
  image_url: 'Image',
  referral_code: 'Referral Code',
  message_602: 'done',
  is_required: 'Required',
  delivery_time: 'Min. Delivery Time',
  delivery_time_max: 'Max. Delivery Time',

  register_your_account: 'Register Your Account',
  confirmation_code: 'Confirmation Code',
  sms_otp: 'Sms Verification Code',
  email_otp: 'Email Verification Code',
  verification: 'Verification',
  spec: 'Spec.',
  promo_expiry_date: 'Expiry Date',
  product: 'Product',

  invalid_amount:
    'The configuration allows you to specify a minimum\n' +
    '      amount,that order totals are required to meet',

  details: 'Description',
  is_visible_in_store: 'Visible In Store',
  is_item_in_stock: 'Item In Stock',
  email_or_phone: 'Email Or Phone',
  for_use: 'For Use',
  item: 'Item',
  barcode: 'Bar Code',
  price: 'Price',
  is_default_selected: 'Default Selected',
  is_user_selected: 'User Selected',
  specifications: 'Specifications',
  item_note_here: 'Item Note Here',

  new_password: 'New Password',
  old_password: 'Old Password',
  country: 'Country',
  city: 'City',
  delivery_type: 'Delivery Type',
  item_name: 'Item Name',

  is_default: 'Visible',
  is_in_stock: 'In Stock',
  is_most_popular: 'Most Popular',
  specification_name: 'Modifier Name',
  specification_type: 'Type',
  specification_detail: 'Detail',
  action: 'Action',
  item_specification_name: 'Item Specification Name',
  select_type: 'Select Type',
  add_specification: 'Add Specification',
  default_select: 'Default Select',
  user_selected: 'User Select',
  type_single: 'Single',
  type_multiple: 'Multiple',

  error_atleast_one_specification: 'Select Atleast One Specification',
  do_not_default_select_morethan_range: 'do not dafault select more than range',

  item_tax: 'Tax on Item',
  is_business_store: 'Business',
  is_business: 'Business',
  is_visible: 'Visible',
  is_busy: 'Busy',
  store_open_time: 'Store Open Time',
  store_close_time: 'Store Close Time',
  free_delivery_for_above_order_price: 'Free Delivery Above Price',
  free_delivery_within_radius: 'Free Delivery Within Radius',
  is_store_pay_delivery_fees: 'Delivery fee on store',

  completed: 'Completed',
  remaining: 'Remaining',

  manual: 'manual',
  social: 'social',

  width: 'Width',
  height: 'Height',

  id: 'Id',
  user: 'User',
  provider: 'Deliveryman',
  payment_by: 'Payment By',
  total: 'Total',
  status: 'Status',
  card: 'Card',
  cash: 'Cash',
  card_on_delivery: 'Card On Delivery',
  user_rating: 'User Rating',
  provider_rating: 'Delivery Man Rating',

  product_name: 'Product Name',
  date_time: 'Date & Time',
  date: 'Date',

  sort: 'Sort',
  search: 'Search',
  date_filter: 'Date Filter',
  ascending: 'Ascending',
  descending: 'Descending',
  filter_id: 'Id',
  filter_name: 'Name',
  value: 'Value',
  expiry_date: 'Expiry Date',
  filter_user: 'User',
  filter_provider: 'Delivery Man',
  filter_item: 'Item',
  filter_product: 'Product',

  please_contact_to_admin: 'Please Contact To Admin',

  order: 'Order',
  service_fees: 'Service Fees',
  order_fees: 'Order Fees',
  store_profit: 'Store Profit',
  paid_service_fee: 'Paid Service Fee',
  recieved_order_payment: 'Recieved Order Payment',
  earning: 'Earning',
  currency: 'Currency',
  admin_earning: 'Admin Earning',
  provider_earning: 'Delivery Man Earning',
  pay_to_provider: 'Pay To Delivery Man',
  pay_store: 'Pay Store',

  completed_order: 'Completed Order',
  cancelled_order: 'Cancelled Order',
  order_amount: 'Order Amount',
  pay_by_admin: 'Pay By Admin',

  ////////// daily earning ///////
  item_price: 'Item Price',
  total_order_price: 'Order Price',
  deduct_from_wallet: 'Deduct from wallet',
  added_in_wallet: 'Added in wallet',
  admin_profit: 'Admin Profit',
  wallet: 'Wallet',
  total_earnings: 'Total Earnings',
  paid_in_wallet: 'PAID IN WALLET',
  paid: 'PAID',
  remaining_to_pay: 'REMAINING TO PAY',
  received_order_amount: 'Received Order Amount',
  pay_to_store: 'Pay To Store',

  payment_status: 'Payment Status',
  no_of_item: 'No Of Item',
  total_cart_price: 'Total Cart Price',
  store_have_service_payment: 'Store Service Payment',
  total_store_income: 'Total Store Income',
  total_order: 'Total Order',
  accepted_order: 'Accepted Order',

  referral_credit: 'Referral Credit',
  total_referred: 'Total Referred',

  all: 'All',
  yes: 'YES',
  no: 'NO',

  doesnot_have_an_account: "Doesn't have an account?",
  store_title1: 'Welcome to',
  app_name: 'yeepeey.',
  store_title2: '',
  signin_to_your_account: 'Sign in to your account',
  forgot_password: 'Forgot Password',

  offer: 'Offer',
  unique_code: 'Unique Code',
  exp_date: 'Exp. Date',

  order_payment_paid_by_store: 'Order Paymnet paid by Store?',
  vehicle: 'Vehicle',

  allow_pasword: 'Ask Password Timer',
  store_sequence: 'Store Sequence',
  ////////

  created_at: 'Created At',
  store_accepted_at: 'Store Accepted At',
  preparing_order_at: 'Preparing Order At',
  order_ready_at: 'Order Ready At',
  store_order_send_at: 'Store Order Send At',
  provider_accepted_at: 'Delivery Man Accepted At',
  completed_at: 'Completed At',
  delivered_at: 'Delivered At',
  start_for_delivery_at: 'Start For Delivery At',
  picked_order_at: 'Picked Order At',
  arrived_on_store_at: 'Arrived On Store At',
  start_for_pickup_at: 'Start for Pickup At',

  //////////////////////////
  base_price: 'Base Price',
  distance_price: 'Distance Price',
  time_price: 'Time Price',
  service_price: 'Service Payment',
  tax_price: 'Tax Price',
  surge_price: 'Surge Price',
  total_delivery_price: 'DELIVERY PRICE',
  promo_bonus: 'Promo Bonus',

  cart_price: 'Cart Price',

  order_payment: 'Order Payment',
  delivery_payment: 'Delivery Payment',

  ///////////

  wallet_payment: 'Wallet Payment',
  cash_payment: 'Cash Payment',
  other_payment: 'Other Payment',
  user_payment: 'User Payment',

  profit: 'Profit',
  items: 'items',
  qty: 'Qty.',
  order_completed: 'ORDER COMPLETED',

  already_account: 'Already have an account?',
  price_rating: 'Price Rating',
  open_full_time: 'Open Full Time',
  open: 'Open',
  sunday: 'Sun',
  monday: 'Mon',
  tuesday: 'Tue',
  wednesday: 'Wed',
  thursday: 'Thu',
  friday: 'Fri',
  saturday: 'Sat',
  required: 'Required',
  add_item_note: 'Add Item Note',

  mobile_no: 'Mobile No.',
  total_service_cost: 'Total Service Cost',
  specification_price: 'Specification Price',
  total_item_cost: 'Total Item Cost',

  first_name: 'First Name',
  last_name: 'Last Name',
  enter_first_name: 'Enter First Name',
  enter_last_name: 'Enter Last Name',
  enter_email: 'Enter Email',
  enter_mobile_no: 'Enter Mobile No.',

  order_cancellation_charge_for_above_order_price: 'Charge Above Price',
  is_order_cancellation_charge_apply: 'Charge',
  order_cancellation_charge_type: 'Charge Type',
  order_cancellation_charge_value: 'Charge Value',
  max_item_quantity_add_by_user: 'Maximum item quantity user can add',
  schedule_order_create_after_minute: 'Min. time after which user can schedule',
  is_provide_delivery_anywhere: 'Provide Delivery Anywhere',
  is_provide_pickup_delivery: 'Provide Pickup Delivery',
  delivery_radius: 'Delivery Radius',
  is_taking_schedule_order: 'Can user schedule order?',
  auto_complete_order: 'Auto Complete Order',
  inform_schedule_order_before_min: 'Notify store before time to prepare order',
  min_order_price: 'Minimum Order Price',
  percentage: 'Percentage',
  absolute: 'Absolute',

  item_image_size_error: 'Image Size Not Proper',
  item_image_ratio_error: 'Image Ratio Not Proper',
  item_image_extension_error: 'Image Extension Not Proper',

  cancel_reason1: 'Order item outof stock',
  cancel_reason2: 'Delivery Adress not reachable',

  promo_code_name: 'Name',
  promo_code_type: 'Type',
  promo_code_value: 'Value',
  order_or_service: 'Order/Service',
  uses: 'Uses',
  user_used: 'User Used',
  state: 'State',
  promo_is_expired: 'Is Expired',
  promo_apply_on: 'Promo Apply On',
  is_active: 'Active',
  is_approved: 'Approved',
  is_promo_required_uses: 'Required Uses',
  is_promo_expiry_date: 'Expiry',
  is_promo_have_minimum_amount_limit: 'Minimum Amount Limit',
  is_promo_have_max_discount_limit: 'Maximum Discount Limit',
  promo_code_uses: 'no Of User to use',
  code_expiry: 'Expiry Date',
  promo_code_apply_on_minimum_amount: 'Minimum Amount',
  promo_code_max_discount_amount: 'Maximum Discount',
  start_date: 'Start Date',
  end_date: 'End Date',
  admin_loyalty: 'Admin Loyality',
  promo_created_loyalty: 'Promo Created Loyality',
  promo_for: 'Promo For',
  admin_loyalty_type: 'Admin Louality Type',
  store: 'Store',

  image_note1: ' Upload max 5 images of size within width x height (min ',
  image_note2: ' and max ',
  image_note3: 'Image ratio should be ',
  image_note4: ' and upload only ',
  image_note5: ' file',
  note_for_image: 'Image Note',

  is_promo_apply_on_completed_order: 'Apply Promo After Complete Order',
  promo_apply_after_completed_order: 'Minimum Complete Order',
  promo_recursion_type: 'Recursion Type',
  is_promo_have_date: 'Date',
  start_time: 'Start Time',
  end_time: 'End Time',
  months: 'Month',
  days: 'Day',
  weeks: 'Week',

  is_promo_have_item_count_limit: 'Minimum Item Limit',
  promo_code_apply_on_minimum_item_count: 'Minimum Item',

  category_already_exist: 'Category Already Exist',
  enter_category_name: 'Enter Category Name',
  enter_product_name: 'Enter Product Name',

  both: 'Both',
  order_type: 'Order Type',
  payment_mode: 'Payment Mode',
  delivery_man: 'Delivery Man',
  pickup: 'Pickup',
  request_id: 'Request ID',
  order_id: 'Order ID',
  rejected: 'Rejected',
  cancelled: 'Cancelled',
  delivery_address: 'Delivery Address',
  assigned_date: 'Assigned Date',

  item_specification: 'Item Modifier',
  specification: 'Modifier',
  specification_group: 'Modifier Group',
  select_file: 'Select File',
  select_image_file: 'Select Image Zip File',
  update_item_specification: 'Update Item Modifier',
  image: 'Image',
};

export var button = {
  download_demo_file: 'Download Demo Excel File',
  add_modifier_group: 'Add Modifier Group',
  submit: 'Submit',
  register: 'Register',
  view_modifier_group: 'View Modifiers',
  view_product: 'View Product',
  login: 'Login',
  login_button: 'LOGIN',
  close: 'Close',
  update: 'Update',
  add_item: 'Add Item',
  add_specification: 'Add Specification',
  add_product: 'Add Product',
  add: 'Add',
  save: 'Save',
  unavailable: 'unavailable',
  edit: 'Edit',
  delete: 'Delete',
  remove: 'Remove',
  change: 'Change',
  select_file: 'Select File',
  add_store_time: 'Add Time',
  update_item: 'Update Item',
  view_specification: 'View Specification',
  view_full_invoice: 'View Full Invoice',

  accept: 'Accept',
  resject: 'Reject',
  prepare_for_order: 'Prepare For Order',
  order_ready: 'Order Ready',
  assign_delivery_for_provider: 'Assign to Delivery Man',
  reassign_delivery_for_provider: 'Reassign',
  cancle: 'Cancel',
  cancel_request: 'Cancel',
  reject: 'Reject',
  view_order_detail: 'View Order Detail',
  view_cart_detail: 'View Cart Detail',
  track_delivery_man: 'Track Delivery Man',
  pre: 'Pre',
  next: 'Next',
  get_confirmation_code: 'Get Confirmation Code',
  apply: 'Apply',
  export_excel: 'Export',
  price_paid_by_store: 'Price Paid By Store',
  ok: 'Ok',
  action: 'Action',
  register_now: 'REGISTER NOW',
  forgot_password: 'Forgot password?',
  sign_up: 'SIGN UP',
  to: 'To',
  edit_order: 'Edit Order',

  add_to_cart: 'Add To Cart',
  cart: 'CART',
  create_order_without_item: 'Create Order Without Item',
  checkout: 'CHECKOUT',
  clear_all: 'clear all',
  place_order: 'Place Order',
  quick_delivery: 'Quick Delivery',
  confirmation_code: 'Confirmation Code',
  complete_order: 'Complete',
  inActive: 'Inactive',
  active: 'Active',
  add_promo: 'Add Promo Code',
  done: 'Done',
  show_all: 'Show All',
  activate: 'Activate',
  cancel: 'Cancel',
  detail: 'Detail',
  invoice: 'Invoice',
  import_data: 'Import Data',
  import_images: 'Import Images',
  add_category: 'Add Category',
};
export var status = {
  created: 'Created',
  waiting_for_accept1: 'Order Created',
  accepted1: 'Accepted',
  start_preparing_order1: 'Start Preparing',
  order_ready1: 'Ready',
  waiting_for_delivery_man1: 'Assigned',
  delivery_man_accepted1: 'Accepted',
  delivery_man_coming1: 'Coming',
  delivery_man_arrived1: 'Arrived',
  picked_order1: 'Picked up',
  started_for_delivery1: 'Delivering',
  arrived_at_destination1: 'Delivering',
  delivered_ordered1: 'Completed',
  assign_order_to_Delivery_man1: 'Assign To Delivery Man',
  no_delivery_man_found1: 'No Found',
  delivery_man_rejected1: 'Rejected',
  delivery_man_cancelled1: 'Rejected',
  user_cancelled1: 'Cancle By User',
  oredr_complete: 'Order Completed',
  order_delivered: 'Delivered',
  completed: 'Completed',
  rejected1: 'Rejected',
  cancelled1: 'Cancelled',
  not_completed: 'Not Completed',
  user_cancelled: 'User cancelled',
  cancelled_request1: 'Not Assigned',

  waiting_for_accept: 'New Order Created',
  accepted: 'Accepted',
  start_preparing_order: 'Started Preparing',
  order_ready: 'Order is ready',
  waiting_for_delivery_man: 'Assigned to Deliveryman',
  delivery_man_accepted: 'Deliveryman accepted',
  delivery_man_coming: 'Deliveryman is coming',
  delivery_man_arrived: 'Deliveryman arrived',
  picked_order: 'Deliveryman picked up order',
  started_for_delivery: 'Delivering',
  arrived_at_destination: 'Deliveryman arrived at destination',
  delivered_ordered: 'Order Delivered',
  assign_order_to_Delivery_man: 'Assign To Delivery Man',
  rejected: 'Store rejected',
  cancelled: 'Store cancelled order',
  no_delivery_man_found: 'Deliveryman not found',
  delivery_man_rejected: 'Deliveryman Rejected',
  delivery_man_cancelled: 'Deliveryman cancelled',
  cancelled_request: 'Request Cancelled',
};

export var message = {
  specification_already_added: 'Specification Already Added',
  item_already_exist: 'Item Already Exist In this Category',
  product_already_exist: 'Product Name Already Exist',
};

export var heading_title = {
  estimated_time_for_ready_order: 'Estimated Time For Ready Order (min)',
  complete_order: 'Complete Order',
  product_title: 'Category Data',
  specification_list: 'Specification list',
  item_title: 'Item Data',
  modifier_group: 'Modifier Group',
  item_setting: 'Item Setting',
  item_specification: 'Item Specification',
  add_item_specification: 'Add Item Specification',
  store_setting_title: 'Store Setting',
  add_store_time: 'Add Store Time',
  history: 'History',
  order_list: 'Order List',
  delivery_list: 'Delivery List',
  item_images: 'Item Images',
  total_earning: 'Total Earning',
  order_earning: 'Order Earning',
  store_transactions: 'Store Transactions',
  other_earning: 'Other Earning',
  orders: 'Orders',
  order_user_detail: 'Order User Detail',
  order_from: 'Order From',
  delivery_to: 'Delivery To',
  payment: 'Payment',
  delivery_man: 'Delivery Man',

  you_are_decline: 'Your Account has been deactivated by admin',
  rating: 'Rating',

  total_order: 'Total Order',
  accepted_order: 'Accepted Order',
  rejected_order: 'Rejected Order',
  completed_order: 'Completed Order',
  total_item_sold: 'Total Item Sold',
  accepted_ratio: 'Accepted Ratio',
  rejected_ratio: 'Rejected Ratio',
  completed_ratio: 'Completed Ratio',
  daily_earning: 'Daily Earning',

  invoice_no: 'Invoice No.',
  user_detail: 'User Detail',
  provider_detail: 'Delivery Man Detail',
  order_detail: 'Order Detail',
  order_status: 'Order Status',
  distance: 'Distance',
  total_time: 'Total Time',
  total_items: 'Total Items',
  delivery_fees: 'DELIVERY FEES',
  total: 'TOTAL',
  quantity: 'QUANTITY',
  price: 'PRICE',
  cart: 'CART',
  order_fees: 'ORDER FEES',
  earning: 'Earning',
  promo_setting: 'Promo Setting',
  promo_data: 'Promo Data',
  product: 'Category',
  category: 'Category',
  item: 'Item',
  add_modifier_group: 'Add Modifier Group',
  ready_to_delivery: 'Ready to Delivery',
  in_progress: 'In-Progress',
  accepted: 'Accepted',
  new_orders: 'New Orders',

  order_price_settings: 'Order Price Settings',
  order_cancellation_settings: 'Order Cancellation Settings',
  schedule_order_settings: 'Schedule Order Settings',
  delivery_settings: 'Delivery Settings',
  store_time: 'Operation Time Settings',
  select_tag: 'Select tags where your expertise lie',
  general_settings: 'General Settings',
  upload_documents: 'Upload Documents',
  add_provider: 'Add Provider',
  p_accepted_order: 'ACCEPTED',
  p_completed_order: 'COMPLETED',
  p_rejected_order: 'REJECTED',
  cancelled_order: 'Cancelled Order',
};
export var lable_title = {
  cash: 'Cash',
  card: 'Card',
  absolute: 'Absolute',
  percentage: 'Percentage',
  order: 'Order',
  service: 'Service',
  active: 'Active',
  inactive: 'Inactive',
  expired: 'Expired',
  not_expired: 'Not Expired',
  store: 'Store',
  admin: 'Admin',
  sub_admin: 'Sub Admin',
  provider: 'Deliveryman',
  user: 'User',
  provider_vehicle_type: 'Delivery Man Vehicle',
  mandatory: 'Mandatory',
  optional: 'Optional',
  completed: 'COMPLETED',
  not_completed: 'NOT COMPLETED',
  delivery_fees_paid_by_store: 'DELIVERY FEES PAID BY STORE',
  asap: 'ASAP',

  created_at: 'Created At',
  store_accepted_at: 'Store Accepted At',
  preparing_order_at: 'Preparing Order At',
  order_ready_at: 'Order Ready At',
  store_order_send_at: 'Store Order Send At',
  provider_accepted_at: 'Delivery Man Accepted At',

  start_for_pickup_at: 'Start for Pickup At',
  arrived_on_store_at: 'Arrived On Store At',
  picked_order_at: 'Picked Order At',
  start_for_delivery_at: 'Start For Delivery At',
  delivered_at: 'Delivered At',
  completed_at: 'Completed At',
};
