export var MESSAGE_CODE = {
  121: 'Register Successfully',
  122: 'Login Successfully',
  123: 'Update Successfully',
  124: 'Password Reset Successfully',
  125: 'Get Otp Successfully',
  127: 'Logout Successfully',
  131: 'Skipped Referral Process',
  132: 'Referral Process Successfully',
  133: 'Store Data Successfully',
  134: 'Store List Get Successfully',
  135: 'Order History Get Successfully',
  136: 'Store Detail Get Successfully',
  137: 'Approved Successfully',
  138: 'Declined Successfully',
  139: 'Get Detail Successfully',
  140: 'Otp Verification Successfully',

  142: 'Give Rating To User Successfully',
  143: 'Give Rating To Provider Successfully',
  144: 'Get Daily Earning Successfully',
  145: 'Get Weekly Earning Successfully',
  146: 'Cancel Request Successfully',
  244: 'Order Assigned to Deliveryman Successfully',
  253: 'Request Completed Successfully',

  381: 'Product Add Successfully',
  382: 'Get Product List Successfully',
  383: 'Product Update Successfully',
  385: 'Product Deleted Successfully',
  391: 'Specification Add Successfully',
  392: 'Get Specification List Successfully',
  393: 'Specification Delete Successfully',

  901: 'Item Add Successfully',
  902: 'Item Image Upload Successfully',
  903: 'Item Image Update Successfully',
  904: 'Get Item List Successfully',
  905: 'Item Update Successfully',
  906: 'Item State Change Successfully',
  908: 'Item Deleted Successfully',
  911: 'Document Add Successfully',
  912: 'Document List Successfully',
  913: 'Document Upload Successfully',
  914: 'Document Update Successfully',
  2041: 'Specification Added Successfully',
  2042: 'Get Specification List Successfully',

  241: 'Order Created Successfully',
  5001: 'Please check email',
  921: 'Add Promo Code Successully',
  923: 'Update Promo code Successfully',

  201: 'Register Successfully',
  222: 'Add Vehicle Successfully',
};
