export var ERROR_CODE = {
  999: 'Token Expired',
  1000: 'Data Not Found',
  2000: 'Token Expired',
  2001: 'Set Password failed',

  601: 'Registration Failed',
  602: 'Email Already Registered',
  603: 'Mobile Number Already Registered',
  605: 'Already Registered With Social',
  606: 'Not Registered With Social',
  611: 'Login Failed',
  612: 'Email or Phone Number Not Registered',
  613: 'Invalid Passowrd',
  621: 'Update Failed',
  623: 'Logout Failed',
  631: 'Invalid Referral Code',
  632: 'Referral Already Used',
  633: 'Referral Process Failed',

  634: 'Store Data Not Found',
  635: 'Store Business Off',
  636: 'Order History Not Found',
  637: 'Order Detail Not Found',
  638: 'Otp Verification Failed',
  639: 'Email And Phone Number Already Registered',
  641: 'Daily Earning Not Found',
  642: 'Weekly Earning Not Found',

  871: 'Add Product Failed',
  872: 'Product Not Found',
  873: 'Update Product Failed',
  875: 'Product Name Already Exist',

  881: 'Specification Add Failed',
  882: 'Specification Not Found',

  891: 'Item Data Add Failed',
  892: 'Item Not Found',
  893: 'Item Image Upload failed',
  894: 'Item Image Update Failed',
  895: 'Item Update Failed',
  896: 'Item Status Changed failed',
  897: 'Item Name Already Used',

  1001: 'Document Add Failed',
  1002: 'Document Not Found',
  1003: 'Document List Not Found',
  1004: 'Document Upload Failed',
  1005: 'Update Failed',

  1041: 'Specification Group Add Failed',
  1042: 'Specification Group List Not Found',
  622: 'Failed to update device token',

  640: 'Pay by cash on delivery failed',

  651: 'Order failed',
  652: 'Order not found',
  653: 'Set order status failed',
  654: 'Request failed',
  655: 'Change order status failed',
  656: 'Order cancel fialed',
  801: 'Country detail not found',
  811: 'City detail not found',
  821: 'App key not found',
  831: 'Setting detail not found',
  845: 'Category data not found',

  426: 'No provider found',
  550: 'Referral code is out of uses limit in your country.',
  541: 'Referral code not valid.',
  547: 'Referral code not valid for your country.',

  2021: 'Adding a bank detail failed.',
  2022: 'Bank detail not found.',
  2023: 'Updating a bank detail failed. ',
  2024: 'Deleting a bank detail failed.',
  815: 'Wallet request details not found.',
  816: 'Wallet request create failed',
  817: 'Wallet request cancelled failed.',
  818: 'Wallet request accepted failed.',
  819: 'Wallet request transferred failed.',
  820: 'Wallet request completed failed.',
  659: 'Order complete failed.',
  961: 'Add in cart failed.',
  965: 'Change delivery address failed.',
  962: 'Cart not found.',
  643: 'Mismatch store id.',
  660: 'Invalid confirmation code.',
  1011: 'Promo code data add failed.',
  1012: 'Promo code data not found.',
  1013: 'Promo update failed.',
  1014: 'Promo list not found.',
  557: 'Your order price less then store minimum order price.',
};
